// @generated - DO NOT EDIT BY HAND
// To update this file, run: npm run update-sources

export type Code = 
  | '0001'
  | '0002'
  | '0003'
  | '0004'
  | '0005'
  | '0006'
  | '0007'
  | '0008'
  | '0009'
  | '0010'
  | '0011'
  | '0012'
  | '0013'
  | '0014'
  | '0015'
  | '0016'
  | '0017'
  | '0018'
  | '0019'
  | '0020'
  | '0021'
  | '0022'
  | '0023'
  | '0024'
  | '0025'
  | '0026'
  | '0027'
  | '0028'
  | '0029'
  | '0030'
  | '0031'
  | '0032'
  | '0033'
  | '0034'
  | '0035'
  | '0036'
  | '0037'
  | '0038'
  | '0039'
  | '0040'
  | '0041'
  | '0042'
  | '0043'
  | '0044'
  | '0045'
  | '0046'
  | '0047'
  | '0048'
  | '0049'
  | '0050'
  | '0051'
  | '0052'
  | '0053'
  | '0054'
  | '0055'
  | '0056'
  | '0057'
  | '0058'
  | '0059'
  | '0060'
  | '0061'
  | '0062'
  | '0063'
  | '0064'
  | '0065'
  | '0066'
  | '0067'
  | '0068'
  | '0069'
  | '0070'
  | '0071'
  | '0072'
  | '0073'
  | '0074'
  | '0075'
  | '0076'
  | '0077'
  | '0078'
  | '0079'
  | '0080'
  | '0081'
  | '0082'
  | '0083'
  | '0084'
  | '0085'
  | '0086'
  | '0087'
  | '0088'
  | '0089'
  | '0090'
  | '0091'
  | '0092'
  | '0093'
  | '0094'
  | '0095'
  | '0096'
  | '0097'
  | '0098'
  | '0099'
  | '0100'
  | '0101'
  | '0102'
  | '0103'
  | '0104'
  | '0105'
  | '0106'
  | '0107'
  | '0108'
  | '0109'
  | '0110'
  | '0111'
  | '0112'
  | '0113'
  | '0114'
  | '0115'
  | '0116'
  | '0117'
  | '0118'
  | '0119'
  | '0120'
  | '0121'
  | '0122'
  | '0123'
  | '0124'
  | '0125'
  | '0126'
  | '0127'
  | '0128'
  | '0129'
  | '0130'
  | '0131'
  | '0132'
  | '0133'
  | '0134'
  | '0135'
  | '0136'
  | '0137'
  | '0138'
  | '0139'
  | '0140'
  | '0141'
  | '0142'
  | '0143'
  | '0144'
  | '0145'
  | '0146'
  | '0147'
  | '0148'
  | '0149'
  | '0150'
  | '0151'
  | '0152'
  | '0153'
  | '0154'
  | '0155'
  | '0156'
  | '0157'
  | '0158'
  | '0159'
  | '0160'
  | '0161'
  | '0162'
  | '0163'
  | '0164'
  | '0165'
  | '0166'
  | '0167'
  | '0168'
  | '0169'
  | '0170'
  | '0171'
  | '0172'
  | '0173'
  | '0174'
  | '0175'
  | '0176'
  | '0177'
  | '0178'
  | '0179'
  | '0180'
  | '0181'
  | '0182'
  | '0183'
  | '0184'
  | '0185'
  | '0186'
  | '0187'
  | '0188'
  | '0189'
  | '0190'
  | '0191'
  | '0192'
  | '0193'
  | '0194'
  | '0195'
  | '0196'
  | '0197'
  | '0198'
  | '0199'
  | '0200'
  | '0201'
  | '0202'
  | '0203'
  | '0204'
  | '0205'
  | '0206'
  | '0207'
  | '0208'
  | '0209'
  | '0210'
  | '0211'
  | '0212'
  | '0213'
  | '0214'
  | '0215'
  | '0216'
  | '0217'
  | '0218'
  | '0219'
  | '0220'
  | '0221'
  | '0222'
  | '0223'
  | '0224'
  | '0225'
  | '0226'
  | '0227'
  | '0228'
  | '0229'
  | '0230'
  | '0231'
  | '0232'
  | '0233'
  | '0234'
  | '0235'
  | '0236'
  | '0237'
  | '0238'
  | '0239'
  | '0240'
  | '0241'
  | '0242'
  | '0243'
  | '0244'
  | '0245'
  | '0246'
  | '0247'
  | '0248'
  | '0249'
  | '0250'
  | '0251'
  | '0252'
  | '0253'
  | '0254'
  | '0255'
  | '0256'
  | '0257'
  | '0258'
  | '0259'
  | '0260'
  | '0261'
  | '0262'
  | '0263'
  | '0264'
  | '0265'
  | '0266'
  | '0267'
  | '0268'
  | '0269'
  | '0270'
  | '0271'
  | '0272'
  | '0273'
  | '0274'
  | '0275'
  | '0276'
  | '0277'
  | '0278'
  | '0279'
  | '0280'
  | '0281'
  | '0282'
  | '0283'
  | '0284'
  | '0285'
  | '0286'
  | '0287'
  | '0288'
  | '0289'
  | '0290'
  | '0291'
  | '0292'
  | '0293'
  | '0294'
  | '0295'
  | '0296'
  | '0297'
  | '0298'
  | '0299'
  | '0300'
  | '0301'
  | '0302'
  | '0303'
  | '0304'
  | '0305'
  | '0306'
  | '0307'
  | '0308'
  | '0309'
  | '0310'
  | '0311'
  | '0312'
  | '0313'
  | '0314'
  | '0315'
  | '0316'
  | '0317'
  | '0318'
  | '0319'
  | '0320'
  | '0321'
  | '0322'
  | '0323'
  | '0324'
  | '0325'
  | '0326'
  | '0327'
  | '0328'
  | '0329'
  | '0330'
  | '0331'
  | '0332'
  | '0333'
  | '0334'
  | '0335'
  | '0336'
  | '0337'
  | '0338'
  | '0339'
  | '0340'
  | '0341'
  | '0342'
  | '0343'
  | '0344'
  | '0345'
  | '0346'
  | '0347'
  | '0348'
  | '0349'
  | '0350'
  | '0351'
  | '0352'
  | '0353'
  | '0354'
  | '0355'
  | '0356'
  | '0357'
  | '0358'
  | '0359'
  | '0360'
  | '0361'
  | '0362'
  | '0363'
  | '0364'
  | '0365'
  | '0366'
  | '0367'
  | '0368'
  | '0369'
  | '0370'
  | '0371'
  | '0372'
  | '0373'
  | '0374'
  | '0375'
  | '0376'
  | '0377'
  | '0378'
  | '0379'
  | '0380'
  | '0381'
  | '0382'
  | '0383'
  | '0384'
  | '0385'
  | '0386'
  | '0387'
  | '0388'
  | '0389'
  | '0390'
  | '0391'
  | '0392'
  | '0393'
  | '0394'
  | '0395'
  | '0396'
  | '0397'
  | '0398'
  | '0399'
  | '0400'
  | '0401'
  | '0402'
  | '0403'
  | '0404'
  | '0405'
  | '0406'
  | '0407'
  | '0408'
  | '0409'
  | '0410'
  | '0411'
  | '0412'
  | '0413'
  | '0414'
  | '0415'
  | '0416'
  | '0417'
  | '0418'
  | '0419'
  | '0420'
  | '0421'
  | '0422'
  | '0423'
  | '0424'
  | '0425'
  | '0426'
  | '0427'
  | '0428'
  | '0429'
  | '0430'
  | '0431'
  | '0432'
  | '0433'
  | '0434'
  | '0435'
  | '0436'
  | '0437'
  | '0438'
  | '0439'
  | '0440'
  | '0441'
  | '0442'
  | '0443'
  | '0444'
  | '0445'
  | '0446'
  | '0447'
  | '0448'
  | '0449'
  | '0450'
  | '0451'
  | '0452'
  | '0453'
  | '0454'
  | '0455'
  | '0456'
  | '0457'
  | '0458'
  | '0459'
  | '0460'
  | '0461'
  | '0462'
  | '0463'
  | '0464'
  | '0465'
  | '0466'
  | '0467'
  | '0468'
  | '0469'
  | '0470'
  | '0471'
  | '0472'
  | '0473'
  | '0474'
  | '0475'
  | '0476'
  | '0477'
  | '0478'
  | '0479'
  | '0480'
  | '0481'
  | '0482'
  | '0483'
  | '0484'
  | '0485'
  | '0486'
  | '0487'
  | '0488'
  | '0489'
  | '0490'
  | '0491'
  | '0492'
  | '0493'
  | '0494'
  | '0495'
  | '0496'
  | '0497'
  | '0498'
  | '0499'
  | '0500'
  | '0501'
  | '0502'
  | '0503'
  | '0504'
  | '0505'
  | '0506'
  | '0507'
  | '0508'
  | '0509'
  | '0510'
  | '0511'
  | '0512'
  | '0513'
  | '0514'
  | '0515'
  | '0516'
  | '0517'
  | '0518'
  | '0519'
  | '0520'
  | '0521'
  | '0522'
  | '0523'
  | '0524'
  | '0525'
  | '0526'
  | '0527'
  | '0528'
  | '0529'
  | '0530'
  | '0531'
  | '0532'
  | '0533'
  | '0534'
  | '0535'
  | '0536'
  | '0537'
  | '0538'
  | '0539'
  | '0540'
  | '0541'
  | '0542'
  | '0543'
  | '0544'
  | '0545'
  | '0546'
  | '0547'
  | '0548'
  | '0549'
  | '0550'
  | '0551'
  | '0552'
  | '0553'
  | '0554'
  | '0555'
  | '0556'
  | '0557'
  | '0558'
  | '0559'
  | '0560'
  | '0561'
  | '0562'
  | '0563'
  | '0564'
  | '0565'
  | '0566'
  | '0567'
  | '0568'
  | '0569'
  | '0570'
  | '0571'
  | '0572'
  | '0573'
  | '0574'
  | '0575'
  | '0576'
  | '0577'
  | '0578'
  | '0579'
  | '0580'
  | '0581'
  | '0582'
  | '0583'
  | '0584'
  | '0585'
  | '0586'
  | '0587'
  | '0588'
  | '0589'
  | '0590'
  | '0591'
  | '0592'
  | '0593'
  | '0594'
  | '0595'
  | '0596'
  | '0597'
  | '0598'
  | '0599'
  | '0600'
  | '0601'
  | '0602'
  | '0603'
  | '0604'
  | '0605'
  | '0606'
  | '0607'
  | '0608'
  | '0609'
  | '0610'
  | '0611'
  | '0612'
  | '0613'
  | '0614'
  | '0615'
  | '0616'
  | '0617'
  | '0618'
  | '0619'
  | '0620'
  | '0621'
  | '0622'
  | '0623'
  | '0624'
  | '0625'
  | '0626'
  | '0627'
  | '0628'
  | '0629'
  | '0630'
  | '0631'
  | '0632'
  | '0633'
  | '0634'
  | '0635'
  | '0636'
  | '0637'
  | '0638'
  | '0639'
  | '0640'
  | '0641'
  | '0642'
  | '0643'
  | '0644'
  | '0645'
  | '0646'
  | '0647'
  | '0648'
  | '0649'
  | '0650'
  | '0651'
  | '0652'
  | '0653'
  | '0654'
  | '0655'
  | '0656'
  | '0657'
  | '0658'
  | '0659'
  | '0660'
  | '0661'
  | '0662'
  | '0663'
  | '0664'
  | '0665'
  | '0666'
  | '0667'
  | '0668'
  | '0669'
  | '0670'
  | '0671'
  | '0672'
  | '0673'
  | '0674'
  | '0675'
  | '0676'
  | '0677'
  | '0678'
  | '0679'
  | '0680'
  | '0681'
  | '0682'
  | '0683'
  | '0684'
  | '0685'
  | '0686'
  | '0687'
  | '0688'
  | '0689'
  | '0690'
  | '0691'
  | '0692'
  | '0693'
  | '0694'
  | '0695'
  | '0696'
  | '0697'
  | '0698'
  | '0699'
  | '0700'
  | '0701'
  | '0702'
  | '0703'
  | '0704'
  | '0705'
  | '0706'
  | '0707'
  | '0708'
  | '0709'
  | '0710'
  | '0711'
  | '0712'
  | '0713'
  | '0714'
  | '0715'
  | '0716'
  | '0717'
  | '0718'
  | '0719'
  | '0720'
  | '0721'
  | '0722'
  | '0723'
  | '0724'
  | '0725'
  | '0726'
  | '0727'
  | '0728'
  | '0729'
  | '0730'
  | '0731'
  | '0732'
  | '0733'
  | '0734'
  | '0735'
  | '0736'
  | '0737'
  | '0738'
  | '0739'
  | '0740'
  | '0741'
  | '0742'
  | '0743'
  | '0744'
  | '0745'
  | '0746'
  | '0747'
  | '0748'
  | '0749'
  | '0750'
  | '0751'
  | '0752'
  | '0753'
  | '0754'
  | '0755'
  | '0756'
  | '0757'
  | '0758'
  | '0759'
  | '0760'
  | '0761'
  | '0762'
  | '0763'
  | '0764'
  | '0765'
  | '0766'
  | '0767'
  | '0768'
  | '0769'
  | '0770'
  | '0771'
  | '0772'
  | '0773'
  | '0774'
  | '0775'
  | '0776'
  | '0777'
  | '0778'
  | '0779'
  | '0780'
  | '0781'
  | '0782'
  | '0783'
  | '0784'
  | '0785'
  | '0786'
  | '0787'
  | '0788'
  | '0789'
  | '0790'
  | '0791'
  | '0792'
  | '0793'
  | '0794'
  | '0795'
  | '0796'
  | '0797'
  | '0798'
  | '0799'
  | '0800'
  | '0801'
  | '0802'
  | '0803'
  | '0804'
  | '0805'
  | '0806'
  | '0807'
  | '0808'
  | '0809'
  | '0810'
  | '0811'
  | '0812'
  | '0813'
  | '0814'
  | '0815'
  | '0816'
  | '0817'
  | '0818'
  | '0819'
  | '0820'
  | '0821'
  | '0822'
  | '0823'
  | '0824'
  | '0825'
  | '0826'
  | '0827'
  | '0828'
  | '0829'
  | '0830'
  | '0831'
  | '0832'
  | '0833'
  | '0834'
  | '0835'
  | '0836'
  | '0837'
  | '0838'
  | '0839'
  | '0840'
  | '0841'
  | '0842'
  | '0843'
  | '0844'
  | '0845'
  | '0846'
  | '0847'
  | '0848'
  | '0849'
  | '0850'
  | '0851'
  | '0852'
  | '0853'
  | '0854'
  | '0855'
  | '0856'
  | '0857'
  | '0858'
  | '0859'
  | '0860'
  | '0861'
  | '0862'
  | '0863'
  | '0864'
  | '0865'
  | '0866'
  | '0867'
  | '0868'
  | '0869'
  | '0870'
  | '0871'
  | '0872'
  | '0873'
  | '0874'
  | '0875'
  | '0876'
  | '0877'
  | '0878'
  | '0879'
  | '0880'
  | '0881'
  | '0882'
  | '0883'
  | '0884'
  | '0885'
  | '0886'
  | '0887'
  | '0888'
  | '0889'
  | '0890'
  | '0891'
  | '0892'
  | '0893'
  | '0894'
  | '0895'
  | '0896'
  | '0897'
  | '0898'
  | '0899'
  | '0900'
  | '0901'
  | '0902'
  | '0903'
  | '0904'
  | '0905'
  | '0906'
  | '0907'
  | '0908'
  | '0909'
  | '0910'
  | '0911'
  | '0912'
  | '0913'
  | '0914'
  | '0915'
  | '0916'
  | '0917'
  | '0918'
  | '0919'
  | '0920'
  | '0921'
  | '0922'
  | '0923'
  | '0924'
  | '0925'
  | '0926'
  | '0927'
  | '0928'
  | '0929'
  | '0930'
  | '0931'
  | '0932'
  | '0933'
  | '0934'
  | '0935'
  | '0936'
  | '0937'
  | '0938'
  | '0939'
  | '0940'
  | '0941'
  | '0942'
  | '0943'
  | '0944'
  | '0945'
  | '0946'
  | '0947'
  | '0948'
  | '0949'
  | '0950'
  | '0951'
  | '0952'
  | '0953'
  | '0954'
  | '0955'
  | '0956'
  | '0957'
  | '0958'
  | '0959'
  | '0960'
  | '0961'
  | '0962'
  | '0963'
  | '0964'
  | '0965'
  | '0966'
  | '0967'
  | '0968'
  | '0969'
  | '0970'
  | '0971'
  | '0972'
  | '0973'
  | '0974'
  | '0975'
  | '0976'
  | '0977'
  | '0978'
  | '0979'
  | '0980'
  | '0981'
  | '0982'
  | '0983'
  | '0984'
  | '0985'
  | '0986'
  | '0987'
  | '0988'
  | '0989'
  | '0990'
  | '0991'
  | '0992'
  | '0993'
  | '0994'
  | '0995'
  | '0996'
  | '0997'
  | '0998'
  | '0999'
  | '1000'
  | '1001'
  | '1002'
  | '1003'
  | '1004'
  | '1005'
  | '1006'
  | '1007'
  | '1008'
  | '1009'
  | '1010'
  | '1011'
  | '1012'
  | '1013'
  | '1014'
  | '1015'
  | '1016'
  | '1017'
  | '1018'
  | '1019'
  | '1020'
  | '1021'
  | '1022'
  | '1023'
  | '1024'
  | '1025'
  | '1026'
  | '1027'
  | '1028'
  | '1029'
  | '1030'
  | '1031'
  | '1032'
  | '1033'
  | '1034'
  | '1035'
  | '1036'
  | '1037'
  | '1038'
  | '1039'
  | '1040'
  | '1041'
  | '1042'
  | '1043'
  | '1044'
  | '1045'
  | '1046'
  | '1047'
  | '1048'
  | '1049'
  | '1050'
  | '1051'
  | '1052'
  | '1053'
  | '1054'
  | '1055'
  | '1056'
  | '1057'
  | '1058'
  | '1059'
  | '1060'
  | '1061'
  | '1062'
  | '1063'
  | '1064'
  | '1065'
  | '1066'
  | '1067'
  | '1068'
  | '1069'
  | '1070'
  | '1071'
  | '1072'
  | '1073'
  | '1074'
  | '1075'
  | '1076'
  | '1077'
  | '1078'
  | '1079'
  | '1080'
  | '1081'
  | '1082'
  | '1083'
  | '1084'
  | '1085'
  | '1086'
  | '1087'
  | '1088'
  | '1089'
  | '1090'
  | '1091'
  | '1092'
  | '1093'
  | '1094'
  | '1095'
  | '1096'
  | '1097'
  | '1098'
  | '1099'
  | '1100'
  | '1101'
  | '1102'
  | '1103'
  | '1104'
  | '1105'
  | '1106'
  | '1107'
  | '1108'
  | '1109'
  | '1110'
  | '1111'
  | '1112'
  | '1113'
  | '1114'
  | '1115'
  | '1116'
  | '1117'
  | '1118'
  | '1119'
  | '1120'
  | '1121'
  | '1122'
  | '1123'
  | '1124'
  | '1125'
  | '1126'
  | '1127'
  | '1128'
  | '1129'
  | '1130'
  | '1131'
  | '1132'
  | '1133'
  | '1134'
  | '1135'
  | '1136'
  | '1137'
  | '1138'
  | '1139'
  | '1140'
  | '1141'
  | '1142'
  | '1143'
  | '1144'
  | '1145'
  | '1146'
  | '1147'
  | '1148'
  | '1149'
  | '1150'
  | '1151'
  | '1152'
  | '1153'
  | '1154'
  | '1155'
  | '1156'
  | '1157'
  | '1158'
  | '1159'
  | '1160'
  | '1161'
  | '1162'
  | '1163'
  | '1164'
  | '1165'
  | '1166'
  | '1167'
  | '1168'
  | '1169'
  | '1170'
  | '1171'
  | '1172'
  | '1173'
  | '1174'
  | '1175'
  | '1176'
  | '1177'
  | '1178'
  | '1179'
  | '1180'
  | '1181'
  | '1182'
  | '1183'
  | '1184'
  | '1185'
  | '1186'
  | '1187'
  | '1188'
  | '1189'
  | '1190'
  | '1191'
  | '1192'
  | '1193'
  | '1194'
  | '1195'
  | '1196'
  | '1197'
  | '1198'
  | '1199'
  | '1200'
  | '1201'
  | '1202'
  | '1203'
  | '1204'
  | '1205'
  | '1206'
  | '1207'
  | '1208'
  | '1209'
  | '1210'
  | '1211'
  | '1212'
  | '1213'
  | '1214'
  | '1215'
  | '1216'
  | '1217'
  | '1218'
  | '1219'
  | '1220'
  | '1221'
  | '1222'
  | '1223'
  | '1224'
  | '1225'
  | '1226'
  | '1227'
  | '1228'
  | '1229'
  | '1230'
  | '1231'
  | '1232'
  | '1233'
  | '1234'
  | '1235'
  | '1236'
  | '1237'
  | '1238'
  | '1239'
  | '1240'
  | '1241'
  | '1242'
  | '1243'
  | '1244'
  | '1245'
  | '1246'
  | '1247'
  | '1248'
  | '1249'
  | '1250'
  | '1251'
  | '1252'
  | '1253'
  | '1254'
  | '1255'
  | '1256'
  | '1257'
  | '1258'
  | '1259'
  | '1260'
  | '1261'
  | '1262'
  | '1263'
  | '1264'
  | '1265'
  | '1266'
  | '1267'
  | '1268'
  | '1269'
  | '1270'
  | '1271'
  | '1272'
  | '1273'
  | '1274'
  | '1275'
  | '1276'
  | '1277'
  | '1278'
  | '1279'
  | '1280'
  | '1281'
  | '1282'
  | '1283'
  | '1284'
  | '1285'
  | '1286'
  | '1287'
  | '1288'
  | '1289'
  | '1290'
  | '1291'
  | '1292'
  | '1293'
  | '1294'
  | '1295'
  | '1296'
  | '1297'
  | '1298'
  | '1299'
  | '1300'
  | '1301'
  | '1302'
  | '1303'
  | '1304'
  | '1305'
  | '1306'
  | '1307'
  | '1308'
  | '1309'
  | '1310'
  | '1311'
  | '1312'
  | '1313'
  | '1314'
  | '1315'
  | '1316'
  | '1317'
  | '1318'
  | '1319'
  | '1320'
  | '1321'
  | '1322'
  | '1323'
  | '1324'
  | '1325'
  | '1326'
  | '1327'
  | '1328'
  | '1329'
  | '1330'
  | '1331'
  | '1332'
  | '1333'
  | '1334'
  | '1335'
  | '1336'
  | '1337'
  | '1338'
  | '1339'
  | '1340'
  | '1341'
  | '1342'
  | '1343'
  | '1344'
  | '1345'
  | '1346'
  | '1347'
  | '1348'
  | '1349'
  | '1350'
  | '1351'
  | '1352'
  | '1353'
  | '1354'
  | '1355'
  | '1356'
  | '1357'
  | '1358'
  | '1359'
  | '1360'
  | '1361'
  | '1362'
  | '1363'
  | '1364'
  | '1365'
  | '1366'
  | '1367'
  | '1368'
  | '1369'
  | '1370'
  | '1371'
  | '1372'
  | '1373'
  | '1374'
  | '1375'
  | '1376'
  | '1377'
  | '1378'
  | '1379'
  | '1380'
  | '1381'
  | '1382'
  | '1383'
  | '1384'
  | '1385'
  | '1386'
  | '1387'
  | '1388'
  | '1389'
  | '1390'
  | '1391'
  | '1392'
  | '1393'
  | '1394'
  | '1395'
  | '1396'
  | '1397'
  | '1398'
  | '1399'
  | '1400'
  | '1401'
  | '1402'
  | '1403'
  | '1404'
  | '1405'
  | '1406'
  | '1407'
  | '1408'
  | '1409'
  | '1410'
  | '1411'
  | '1412'
  | '1413'
  | '1414'
  | '1415'
  | '1416'
  | '1417'
  | '1418'
  | '1419'
  | '1420'
  | '1421'
  | '1422'
  | '1423'
  | '1424'
  | '1425'
  | '1426'
  | '1427'
  | '1428'
  | '1429'
  | '1430'
  | '1431'
  | '1432'
  | '1433'
  | '1434'
  | '1435'
  | '1436'
  | '1437'
  | '1438'
  | '1439'
  | '1440'
  | '1441'
  | '1442'
  | '1443'
  | '1444'
  | '1445'
  | '1446'
  | '1447'
  | '1448'
  | '1450'
  | '1451'
  | '1452'
  | '1453'
  | '1454'
  | '1455'
  | '1456'
  | '1457'
  | '1458'
  | '1459'
  | '1460'
  | '1461'
  | '1462'
  | '1463'
  | '1464'
  | '1465'
  | '1466'
  | '1467'
  | '1468'
  | '1469'
  | '1470'
  | '1471'
  | '1472'
  | '1473'
  | '1474'
  | '1475'
  | '1476'
  | '1477'
  | '1478'
  | '1479'
  | '1480'
  | '1481'
  | '1482'
  | '1483'
  | '1484'
  | '1485'
  | '1486'
  | '1487'
  | '1488'
  | '1489'
  | '1490'
  | '1491'
  | '1492'
  | '1493'
  | '1494'
  | '1495'
  | '1496'
  | '1497'
  | '1498'
  | '1499'
  | '1500'
  | '1501'
  | '1502'
  | '1503'
  | '1504'
  | '1505'
  | '1506'
  | '1507'
  | '1508'
  | '1509'
  | '1510'
  | '1511'
  | '1512'
  | '1513'
  | '1514'
  | '1515'
  | '1516'
  | '1517'
  | '1518'
  | '1519'
  | '1520'
  | '1521'
  | '1522'
  | '1523'
  | '1524'
  | '1525'
  | '1526'
  | '1527'
  | '1528'
  | '1529'
  | '1530'
  | '1531'
  | '1532'
  | '1533'
  | '1534'
  | '1535'
  | '1536'
  | '1537'
  | '1538'
  | '1539'
  | '1540'
  | '1541'
  | '1542'
  | '1543'
  | '1544'
  | '1545'
  | '1546'
  | '1547'
  | '1548'
  | '1549'
  | '1550'
  | '1551'
  | '1552'
  | '1553'
  | '1554'
  | '1555'
  | '1556'
  | '1557'
  | '1558'
  | '1559'
  | '1560'
  | '1561'
  | '1562'
  | '1563'
  | '1564'
  | '1570'
  | '1571'
  | '1572'
  | '1573'
  | '1574'
  | '1575'
  | '1576'
  | '1577'
  | '1578'
  | '1579';

export type Display = 
  | 'Ablation par radiofréquence de trouble du rythme et de conduction'
  | 'Accident vasculaire cérébral aigu (AVC)'
  | 'Accueil brûlé en attente de transfert'
  | 'Accueil grand brûlé en attente de transfert'
  | 'Accueil mort inattendue du nourrisson (MIN)'
  | 'Décontamination bactériologique (NRBC)'
  | 'Décontamination chimique (NRBC)'
  | 'Décontamination patient irradié ou radio contaminé (NRBC)'
  | 'Accueil petit brûlé en urgence'
  | 'Accueil traumatisé grave - polytraumatisé'
  | 'Radiothérapie métabolique (iode 131, hyperthyroïdies)'
  | 'Addictologie'
  | 'Examen victime d\'agression sexuelle'
  | 'Aide médicale à la procréation (AMP)'
  | 'Diagnostic Pré Implantatoire (DPI) (Aide Médicale à la Procréation, AMP)'
  | 'Insémination Intra Utérine avec sperme de Conjoint (IIU)'
  | 'Maturation In Vitro (MIV) (Aide Médicale à la Procréation, AMP)'
  | 'Andrologie'
  | 'Echo-repérage'
  | 'Angiographie oculaire (artériographie oculaire)'
  | 'Angioplastie des artères des membres'
  | 'Angioplastie des artères thoraco-abdomino-pelviennes'
  | 'Annuloplastie et valvuloplastie cardiaque'
  | 'Aponévrotomie percutanée palmaire et digitale (maladie de Dupuytren)'
  | 'Arthroplastie hémophilique'
  | 'Arthroscopie'
  | 'Autogreffe de germe de dent'
  | 'Autogreffe de trachée'
  | 'Autopsie'
  | 'Autopsie médico légale'
  | 'Autotransfusion peropératoire (Cell Saver)'
  | 'Bilan de chute'
  | 'Evaluation de la mémoire (bilan mémoire)'
  | 'Exploration urodynamique'
  | 'Biochimie générale'
  | 'Biochimie spécialisée'
  | 'Biologie moléculaire'
  | 'Biopsie artère temporale (BAT)'
  | 'Biopsie des glandes salivaires'
  | 'Biothérapie des connectivites'
  | 'Biothérapie rhumatismes inflammatoires chroniques'
  | 'Soins brûlure oculaire caustique ou thermique'
  | 'Caustique (ingestion)'
  | 'Délivrance de traitement de substitution aux opiacés'
  | 'Chimio-embolisation'
  | 'Chimiothérapies des hémopathies malignes'
  | 'Chirurgie aiguë des brûlures'
  | 'Chirurgie arthroscopique membre inférieur'
  | 'Chirurgie arthroscopique membre supérieur'
  | 'Chirurgie bariatrique majeure : by pass gastrique, sleeve gastrectomie'
  | 'Chirurgie bariatrique (de l\'obésité) mineure : anneau gastrique ajustable'
  | 'Chirurgie bariatrique (obésité)'
  | 'Chirurgie carcinologique dermatologique'
  | 'Chirurgie carcinologique gynécologique'
  | 'Chirurgie carcinologique maxillo-faciale et stomatologique'
  | 'Chirurgie carcinologique ophtalmologique'
  | 'Chirurgie carcinologique orthopédique'
  | 'Chirurgie carcinologique oto-rhino-laryngologique (ORL) et cervico-faciale'
  | 'Chirurgie carcinologique thoracique et pulmonaire'
  | 'Chirurgie carcinologique urologique'
  | 'Chirurgie des tumeurs vasculaires'
  | 'Chirurgie carcinologique viscérale et digestive'
  | 'Chirurgie coronarienne robotique'
  | 'Chirurgie costale'
  | 'Chirurgie oncologique des cancers digestifs avec atteinte péritonéale'
  | 'Chirurgie de la cataracte - implants mono focaux et toriques'
  | 'Chirurgie de la main'
  | 'Chirurgie SOS main (Agrément FESUM)'
  | 'Chirurgie embolie pulmonaire et HTAP post-embolique'
  | 'Chirurgie de la parathyroide'
  | 'Chirurgie de la prostate'
  | 'Chirurgie oncologique du pancréas'
  | 'Chirurgie de la thyroïde'
  | 'Chirurgie de la trachée (oncologique, sténose et fistule trachéo-oesophagienne)'
  | 'Chirurgie de la vessie et des voies urinaires'
  | 'Chirurgie de l\'aorte sous ombilicale'
  | 'Chirurgie de l\'aorte thoracique'
  | 'Chirurgie de l\'articulation temporo-mandibulaire'
  | 'Chirurgie de l\'endométriose'
  | 'Chirurgie de l\'infertilité féminine'
  | 'Chirurgie de tumeurs neuroendocrines'
  | 'Chirurgie dermatologique'
  | 'Chirurgie endoscopique des cordes vocales'
  | 'Chirurgie malformations congénitales cardiaques et vaisseaux supra cardiaques'
  | 'Chirurgie des muscles oculomoteurs (diplopie, strabisme)'
  | 'Chirurgie des nerfs périphériques'
  | 'Chirurgie réparatrice des séquelles de brûlures'
  | 'Chirurgie des syndromes d\'apnée du sommeil (SAS)'
  | 'Chir tumeurs base du crâne, mâchoires et cou (dont angiome, dysplasie cutanée)'
  | 'Chirurgie des varices'
  | 'Chirurgie des vertiges'
  | 'Chirurgie du cristallin'
  | 'Chirurgie du glaucome'
  | 'Chirurgie du pied'
  | 'Chirurgie du pied diabétique'
  | 'Chirurgie du pneumothorax'
  | 'Chirurgie du rachis'
  | 'Chirurgie du rachis en urgence'
  | 'Chirurgie du rachis instrumentée'
  | 'Chirurgie du rachis instrumentée et par technique mini-invasive'
  | 'Chirurgie du rachis par technique mini-invasive'
  | 'Chirurgie du rein par radiofréquence'
  | 'Chirurgie du thymus et des tumeurs du mediastin'
  | 'Chirurgie endocrinienne'
  | 'Chirurgie et plastie de muscle oculomoteur'
  | 'Chirurgie et réparation des voies lacrymales'
  | 'Chirurgie maxillo-faciale et stomatologie'
  | 'Chirurgie orbitaire'
  | 'Chirurgie orthopédique des maladies osseuses constitutionnelles'
  | 'Chirurgie orthopédique du handicap'
  | 'Chirurgie orthopédique et traumatologie'
  | 'Chirurgie orthopédique septique'
  | 'Chirurgie pelvienne robotique'
  | 'Chirurgie plastique du pied diabétique'
  | 'Chirurgie plastique et réparatrice de la paroi thoracique'
  | 'Chirurgie plastique et réparatrice de la trachée et des bronches'
  | 'Chirurgie plastique et réparatrice du sein'
  | 'Chirurgie prostatique par laser'
  | 'Chirurgie prothétique du membre inférieur'
  | 'Chirurgie prothétique du membre supérieur'
  | 'Chirurgie reconstructrice maxillo-faciale et stomatologique'
  | 'Chirurgie réfractive'
  | 'Chirurgie septique de la main'
  | 'Chirurgie thoracique et pulmonaire'
  | 'Chirurgie urologique (urologie)'
  | 'Chirurgie valvulaire robotique'
  | 'Chirurgie viscérale et digestive'
  | 'Chirurgie vitréo-rétinienne'
  | 'Cimentoplastie'
  | 'Cinétique biologique au cours et décours de l\'effort'
  | 'Circulation extracorporelle pour assistance circulatoire-respiratoire (ECMO)'
  | 'Circulation extracorporelle pour assistance circulatoire-respiratoire (ECMO) péd'
  | 'Coeur artificiel (assistance cardiaque)'
  | 'Complications immuno hématologiques chez le malade immunodéprimé'
  | 'Complications infectieuses chez le malade immunodéprimé'
  | 'Complications pulmonaires chez le malade immunodéprimé (pneumo-hématologie)'
  | 'Compression médullaire non traumatique'
  | 'Compression médullaire traumatique'
  | 'Confection d\'orthèse du membre inférieur'
  | 'Confection d\'orthèse du rachis'
  | 'Conseil conjugal'
  | 'Consultation sommeil et travail'
  | 'Contactologie - lentille souple'
  | 'Contrepulsion par ballon intraaortique (CPBIA)'
  | 'Coronarographie'
  | 'Correction des ambiguïtés sexuelles'
  | 'Cosmétologie dentaire (blanchiement, facettes)'
  | 'Test de marche 6 minutes'
  | 'Cystographie pédiatrique'
  | 'Dacryoscanner'
  | 'Déficits immunitaires primitifs et secondaires'
  | 'Dégénerescence maculaire liée à l\'âge (DMLA)'
  | 'Evaluation et traitement du délabrement cutanéo-musculaire'
  | 'Dépistage de la rétinopathie diabétique'
  | 'Dérivation urinaire en urgence sans urétéroscopie (sonde double J en urgence)'
  | 'Dermato-allergologie'
  | 'Dermatologie'
  | 'Dermatologie buccale'
  | 'Dermatologie infectieuse, parasitaires et tropicale'
  | 'Dermatoses bulleuses'
  | 'Dermatoses inflammatoires (psoriasis, eczéma)'
  | 'Dermolipectomie'
  | 'Resurfaçage cutané (laserbration, peeling…)'
  | 'Destruction tumorale sous échographie-TDM-IRM'
  | 'Diabète gestationnel'
  | 'Diagnostic prénatal'
  | 'Nutrition du sportif'
  | 'Dispensation des médicaments aux patients ambulatoires'
  | 'Dépistage et prise en charge du dopage'
  | 'Drépanocytose'
  | 'Dysmorphie maxillo-faciale et stomatologique (hypertrophie, atrophie...)'
  | 'ECG (électrocardiographie)'
  | 'Echange plasmatique - Plasma filtration'
  | 'Echo-doppler ostéoarticulaire'
  | 'Echo-endoscopie broncho-pulmonaire (bronchique)'
  | 'Echographie cardiaque de stress : échographie Dobutamine'
  | 'Echographie cardiaque d\'effort'
  | 'Echographie cardiaque transoesophagienne (ETO)'
  | 'Echographie endo-coronaire'
  | 'Echographie obstétricale 1er trimestre'
  | 'Echographie obstétricale 2nd et 3ème trimestres'
  | 'Education thérapeutique labellisée du patient asthmatique (école de l\'asthme)'
  | 'Electro-convulsivothérapie (ECT, sismothérapie)'
  | 'Embolisation dans le territoire abdomino-pelvien'
  | 'Embolisation dans le territoire thoracique'
  | 'Embolisation dans les territoires neuro-encéphalique et rachidien'
  | 'Embolisation de fibrome'
  | 'Embolisation hépatique'
  | 'Endoscopie de l\'appareil génital féminin (hystéroscopie)'
  | 'Endoscopie de l\'utérus gravide'
  | 'Endo des voies biliaires et du pancréas : cathétérisme rétrograde et ponction'
  | 'Endoscopie digestive basse (coloscopie, rectosigmoïdoscopie)'
  | 'Endoscopie digestive diagnostique et interventionnelle : mucosectomie'
  | 'Endoscopie digestive diagnostique et interventionnelle : pose d\'endoprothèse'
  | 'Endoscopie digestive par vidéo capsule'
  | 'Entrainement électro-systolique externe (EES)'
  | 'Entrainement électro-systolique provisoire'
  | 'Epidémiologie'
  | 'Epreuve d\'effort'
  | 'Epreuve d\'effort cardio-pneumo-métabolique (VO2max)'
  | 'Ergonomie'
  | 'Ethique clinique'
  | 'Evaluation des syndromes démentiels et troubles du comportement'
  | 'Evaluation gériatrique standardisée'
  | 'Elastographie hépatique (fibroscan)'
  | 'Evaluation suivi post accident avec exposition au sang (AES)'
  | 'Eviscération, énucléation du globe oculaire'
  | 'Expertise médicale'
  | 'Exploration électrophysiologique endocavitaire'
  | 'Exploration fonctionnelle respiratoire d\'exercice avec mesure échanges gazeux'
  | 'Femme enceinte drépanocytaire'
  | 'FIV (Féconcation In Vitro)'
  | 'FIV avec Injection Intra Cytoplasmique de Spermatozoïdes (ICSI) (AMP)'
  | 'Formation dialyse'
  | 'Formation sauveteurs - secouristes du travail'
  | 'Gamma-angiographie cardiaque, tomographie cavitaire'
  | 'Génétique chromosomique et moléculaire ante natale (constitutionnelle)'
  | 'Génétique chromosomique et moléculaire post natale (constitutionnelle)'
  | 'Génétique constitutionnelle'
  | 'Gestion des antidotes'
  | 'Greffe cartilagineuse'
  | 'Greffe cutanée en sandwich'
  | 'Greffe de cellules souches hématopoïétiques allogreffe'
  | 'Greffe de cellules souches hématopoïétiques autogreffe'
  | 'Greffe de cornée'
  | 'Greffe de culture de kératinocytes pour brûlure'
  | 'Greffe de membrane amniotique'
  | 'Greffe du visage'
  | 'Greffe méniscale'
  | 'Prise en charge de la maladie du Greffon contre l\'hôte (GVH)'
  | 'Grossesse et VIH'
  | 'Grossesses à risques (pathologiques)'
  | 'Groupe de parole'
  | 'Hémobiologie'
  | 'Hemodialyse intermittente'
  | 'Hemofiltration - hémodiafiltration continue'
  | 'Hémoglobinopathies'
  | 'Hémopathies rares'
  | 'Hémophilie'
  | 'Hépatectomie avec radiofréquence per-opératoire'
  | 'Hépatectomie hyperélargie (ex vivo, in vivo CEC, refroidissement)'
  | 'Homéopathie'
  | 'Hypothermie induite'
  | 'Hystérographie'
  | 'Imagerie pédiatrique avec sédation'
  | 'Imagerie pédiatrique sans sédation'
  | 'Imagerie vasculaire diagnostique et interventionnelle : artériographie'
  | 'Implantation de pompes à baclofène'
  | 'Implantation d\'un défibrillateur cardiaque'
  | 'Implantation d\'un stimulateur cardiaque : pace maker'
  | 'Pose d\'implants dentaires (implantologie)'
  | 'Pose d\'implants cochléaires'
  | 'Traitement des leucémies aiguës par induction'
  | 'Infection par le VIH'
  | 'Infection VIH'
  | 'Infections sexuellement transmissibles (IST)'
  | 'Infiltration articulaire, péri-tendineuse et péri-nerveuse guidée par imagerie'
  | 'Infiltration articulaire radio-guidée'
  | 'Infiltration du rachis cervical'
  | 'Infiltration du rachis thoraco-lombaire-sacré guidée par imagerie'
  | 'Injection de toxine botulique'
  | 'Injection de toxine botulique dans les muscles oculomoteurs'
  | 'Injection intra-articulaire de produit de contraste'
  | 'Injection intravitréenne (IVT)'
  | 'Injection péridurale de sang autologue (blood patch)'
  | 'Interruption de grossesse pour motif médical (IMG/ITG)'
  | 'Interruption volontaire de grossesse (IVG) chirurgicale'
  | 'Interruption volontaire de grossesse (IVG) médicamenteuse'
  | 'IRM foetale'
  | 'Isocinétisme'
  | 'Isolement de secteur (cohorting)'
  | 'Physiothérapie (Kinésithérapie-thermothérapie)'
  | 'Désinvagination par lavement en imagerie'
  | 'Lissage cutané (Lifting)'
  | 'Lithotritie biliaire'
  | 'Lithotritie extracorporelle rénale'
  | 'Lithotritie extracorporelle rénale (LEC)'
  | 'Lymphoscintigraphie'
  | 'Maladie autoimmune'
  | 'Maladie de la thyroïde'
  | 'Maladie de l\'hypophyse'
  | 'Maladie des surrénales'
  | 'Maladie du métabolisme (syndrome métabolique)'
  | 'Maladie rare'
  | 'Maladie systémique'
  | 'Maladies rares : maladies héréditaires du métabolisme'
  | 'Maladies rares : maladies neuromusculaires'
  | 'Maladies virales chroniques (VHC, HPV)'
  | 'Maladies virales chroniques (VHC, HPV, autres)'
  | 'Prise en charge de la maltraitance et violence'
  | 'Manométrie grêlique'
  | 'Manométrie anorectale'
  | 'Médecine aéronautique'
  | 'Médecine aérospatiale'
  | 'Médecine alternative et traitement de la douleur'
  | 'Médecine d\'altitude (médecine de montagne)'
  | 'Médecine des expatriés'
  | 'Médecine des gens de mer'
  | 'Médecine interne gériatrique'
  | 'Traitement par mésothérapie'
  | 'Mesure de force musculaire locale'
  | 'Mesure de pression des loges musculaires (syndrome des loges)'
  | 'Mesure des plis cutanés'
  | 'Microbiologie : bactériologie'
  | 'Microbiologie : mycologie'
  | 'Microbiologie : virologie'
  | 'Microbiologie laboratoire P3'
  | 'Microbiologie laboratoire P4'
  | 'Mort inattendue du nourisson (MIN)'
  | 'Mucoviscidose'
  | 'Chirurgie réparatrice de mutilations sexuelles (excision)'
  | 'Greffe de tympan (myringoplastie ou tympanoplastie)'
  | 'Nécrolyse épidermique (syndromes de Lyell et Stevens-Johnson)'
  | 'Nécrose secondaire au purpura fulminans'
  | 'Neurochirurgie de la douleur'
  | 'Neurochirurgie éveillée avec mapping cortical'
  | 'Neurochir vasculaire (avec compétences neurochirurgicales et endovasculaires)'
  | 'Neurogériatrie'
  | 'Neuro-imagerie fonctionnelle, spectroscopie, tractographie'
  | 'Neuromodulation sacrée'
  | 'Neuro-oncologie (avec accès à RCP et traitement multimodal)'
  | 'Neuro-ophtalmologie (affection oculaire d\'origine neurologique)'
  | 'Neuro-orthopédie'
  | 'Neuro-urologie'
  | 'Nucléotomie transcutanée'
  | 'Nutrition parentérale'
  | 'Obésité'
  | 'Occlusodontie'
  | 'Odontologie chez le patient avec trouble de la coagulation, hémophilie'
  | 'Odontologie médico-légale'
  | 'Onco-génétique'
  | 'Oncogériatrie'
  | 'Oncologie (cancérologie) dermatologique'
  | 'Oncologie (cancérologie) digestive et viscérale'
  | 'Oncologie (cancérologie) gynécologique'
  | 'Oncologie (cancérologie) hématologique'
  | 'Oncologie (cancérologie) oto-rhino-laryngologique (ORL) et cervico-faciale'
  | 'Oncologie (cancérologie) pneumologique'
  | 'Oncologie (cancérologie) rhumatologique'
  | 'Oncologie (cancérologie) sénologique'
  | 'Oncologie (cancérologie) urologique'
  | 'Chirurgie du transsexualisme'
  | 'Ophtalmologie en urgence (hors unité d\'accueil des urgences ophtalmologiques)'
  | 'Orthogénie - Planification et contrôle des naissances'
  | 'Ostéodensitométrie (densitométrie osseuse)'
  | 'Ostéopathie'
  | 'Oto-rhino-laryngologie (ORL)'
  | 'Oto-rhino-laryngologie en urgence (hors unité d\'accueil des urgences ORL)'
  | 'Chirurgie à visée implantaire (dont greffe et comblement de sinus)'
  | 'Pathologie des glandes salivaires'
  | 'Pathologie des ongles (onycologie)'
  | 'Pathologie du cuir chevelu'
  | 'Pathologie infectieuse maxillo-faciale et bucco-dentaire'
  | 'Pathologie liée à l\'obésité'
  | 'Pathologie vulvaire'
  | 'Pelvipérinéologie : incontinence urinaire'
  | 'Pelvipérinéologie : prolapsus génital, rectal, vésical'
  | 'Pharmacologie et toxicologie médico-légale'
  | 'Pharmacologie-épidémiologie'
  | 'Phoniatrie'
  | 'Pied diabétique'
  | 'Soins des plaies chroniques et pansements complexes'
  | 'Plastie de la vulve et du périnée'
  | 'Plastie pénienne'
  | 'Plateforme hospitalière de génétique moléculaire des cancers INCA'
  | 'Pneumopathies interstitielles (infiltrantes)'
  | 'Podologie'
  | 'Ponction biopsie sous repérage guidé'
  | 'Ponction biopsie hépatique (PBH) transjugulaire'
  | 'Ponction biopsie mammaire (sein) : macrobiopsie - microbiopsie'
  | 'Ponction biopsie rénale (PBR) transcutanée'
  | 'Ponction biopsie rénale (PBR) transjugulaire'
  | 'Ponction de ganglion lymphatique'
  | 'Aspiration et / ou Biopsie de moelle osseuse'
  | 'Ponction, biopsie et prélèvement sur le foetus et l\'utérus gravide'
  | 'Pontage des artères des membres'
  | 'Pose de chambre implantable (CIP) percutanée'
  | 'Pose radiologique de filtre cave'
  | 'Pose de système diffuseur implantable pour insulinothérapie intrapéritonéale'
  | 'Pose d\'implant de l\'oreille moyenne'
  | 'Dérivation porto-cave par voie transjugulaire (TIPS)'
  | 'Prélèvement d\'organes : coeur'
  | 'Prélèvement d\'organes à coeur arrêté'
  | 'Prélèvement d\'organes à coeur battant (mort cérébrale)'
  | 'Prélèvement d\'organes sur personne vivante : foie'
  | 'Prélèvement d\'organes sur personne vivante : poumon'
  | 'Prélèvement d\'organes sur personne vivante : rein'
  | 'Prélèvement multi organes (PMO)'
  | 'Préparation des médicaments radiopharmaceutiques'
  | 'Prise en charge de la dysfonction érectile'
  | 'Prise en charge de l\'hémorragie digestive'
  | 'Pose de ballon intra-gastrique (traitement de l\'obésité - bariatrique)'
  | 'Prise en charge des toxicomanes'
  | 'Prise en charge des ventilés chroniques'
  | 'Prise en charge traumatisé grave - polytraumatisé'
  | 'Proctologie'
  | 'Proctologie : traitement chirurgical'
  | 'Proctologie : traitement instrumental'
  | 'Implantation prothèse pénienne'
  | 'Implantation prothèse urètre'
  | 'Psychodynamique du travail'
  | 'Psychogériatrie'
  | 'Psychopathologie du sportif'
  | 'PUVAthérapie'
  | 'Radiochirurgie stéréotaxique'
  | 'Radioprotection'
  | 'Dérivation porto-cave par voie chirurgicale'
  | 'Réalisation des préparations pour essais cliniques'
  | 'Réalisation, désobstruction et ablation de fistules artério-veineuses'
  | 'Reconstruction artérielle des membres'
  | 'Recueil, traitement de gamètes issus de dons'
  | 'Rééducation basse vision'
  | 'Rééducation orthoptique'
  | 'Réhabilitation respiratoire'
  | 'Ré-implantation de doigts'
  | 'Ré-implantation de main'
  | 'Ré-implantation du membre inférieur'
  | 'Ré-implantation du membre supérieur'
  | 'Ré-implantation uretère'
  | 'Remplacement valvulaire par voie percutanée'
  | 'Chirurgie des fentes et des malformations crânio-faciales et de leurs séquelles'
  | 'Réparation de perte de substance par lambeau libre, avec anastomoses vasculaires'
  | 'Revascularisation des artères rénales et-ou viscérales (chirurgie ou stent)'
  | 'Revascul troncs supra-aortiques, artère sous-clavière, artère vertébrale'
  | 'Radiculographie'
  | 'Scintigraphie au 18F-choline (suivi cancer de prostate)'
  | 'Scintigraphie au 18F-DOPA (explorations tumeur endocrine)'
  | 'Scintigraphie au 18F-FDG'
  | 'Scintigraphie rénale'
  | 'Scintigraphie au MIBG'
  | 'Scintigraphie aux hématies marquées (recherche de saignement)'
  | 'Scintigraphie de la neurotransmission dopaminergique (Dat-scan)'
  | 'Scintigraphie de perfusion à l\'ECD (bilan de démence)'
  | 'Scintigraphie de perfusion avec test au Captopril et au Lasilix'
  | 'Scintigraphie des récepteurs à la somatostatine (Octreoscan)'
  | 'Scintigraphie myocardique à l\'effort ou pharmacologique'
  | 'Scintigraphie SPECT-CT'
  | 'Scolarisation sur site'
  | 'Sevrage'
  | 'Soins odontologiques sous anesthésie générale (AG)'
  | 'Soins avec administration de MEOPA'
  | 'Méthode de relaxation'
  | 'Spectroscopie par résonance magnétique (SRM) cérébrale'
  | 'Sport et handicap'
  | 'Sportif de haut niveau'
  | 'Stimulation cérébrale profonde (neurostimulation invasive)'
  | 'Neuro Stimulation Electrique Transcutanée (TENS)'
  | 'Synoviorthèse isotopique'
  | 'Tabacologie'
  | 'Technique d\'épuration extra-rénale'
  | 'Télécrâne'
  | 'Test de fatigabilité local'
  | 'Test d\'effort'
  | 'Test d\'hyperventilation isocapnique'
  | 'Test d\'inclinaison (tilt test)'
  | 'Test en hypoxie'
  | 'Tests allergologiques cutanés'
  | 'Tests allergologiques de provocation'
  | 'Thrombectomie'
  | 'Thrombolyse par voie veineuse'
  | 'Toxicologie'
  | 'Toxicologie clinique des métaux lourds'
  | 'Traitement de la rage post exposition'
  | 'Traitement des infections ostéo-articulaires complexes (CRIOA, CRIOAC)'
  | 'Lithotritie intracorporelle rénale par laser'
  | 'Eval, ttt et suivi des Maladies Inflammatoires Chroniques de l\'Intestin (MICI)'
  | 'Traitement non invasif des tendinopathies par ondes de choc radiales'
  | 'Traitement interventionnel des syndromes caves supérieurs'
  | 'Orthèse pour traitement de l\'apnée du sommeil'
  | 'Transit oeso-gastro-duodénal (TOGD) pédiatrique'
  | 'Transplantation cardiaque (greffe)'
  | 'Transplantation cardio-pulmonaire (greffe)'
  | 'Transplantation hépatique (greffe)'
  | 'Transplantation intestin grêle (greffe)'
  | 'Transplantation pancréatique (greffe)'
  | 'Transplantation pulmonaire (greffe)'
  | 'Transplantation rénale et pancréatique (greffe)'
  | 'Transplantation rénale (greffe)'
  | 'Traumatologie maxillo-faciale et bucco-dentaire'
  | 'Troubles de l\'hémostase et de la coagulation constitutionnels et acquis'
  | 'Bilan des troubles des apprentissages (troubles dys)'
  | 'Prise en charge des troubles du comportement alimentaire (TCA)'
  | 'Evaluation des troubles du sommeil (polysomnographie)'
  | 'Tumeur base du crâne (techniques classiques et endoscopie)'
  | 'Unité centralisée de préparation des médicaments cytotoxiques'
  | 'Unité d\'Accueil de Jeunes Victimes (UAJV)'
  | 'Urgences céphalées'
  | 'Urgences dermatologiques'
  | 'Urgences endocrinologiques'
  | 'Urgences gériatriques'
  | 'Urgences hématologiques'
  | 'Urgences main'
  | 'Urgences maxillo-faciales et stomatologiques'
  | 'Urgences odontologiques (dentaires)'
  | 'Urgences ophtalmologiques'
  | 'Urgences Oto-rhino-laryngologie en urgence (ORL)'
  | 'Urgences psychiatriques'
  | 'Vaccination : encéphalite japonaise'
  | 'Vaccination : fièvre jaune'
  | 'Vaccination antirabique (rage) post-exposition'
  | 'Vaccinations des voyageurs'
  | 'Ventilation en poumons séparés'
  | 'Ventilation par oscillations à haute fréquence (HFO)'
  | 'Ventilation percussive à haute fréquence (HFPV)'
  | 'Vertébroplastie'
  | 'Vertébroplastie - cimentoplastie'
  | 'Acupuncture'
  | 'Chirurgie esthétique maxillo-faciale et stomatologique'
  | 'Chirurgie plastique, reconstructrice et esthétique'
  | 'Dialyse péritonéale'
  | 'Hypnose'
  | 'Lipoaspiration'
  | 'Manométrie oesophagienne'
  | 'Phlébectomie'
  | 'Ponction et biopsie d\'un os et d\'une articulation de membre'
  | 'Pontage coronarien'
  | 'Scintigraphie parathyroïdienne'
  | 'Sialographie'
  | 'Thoracoscopie'
  | 'Hypertension artérielle (HTA)'
  | 'Prise en charge de la tuberculose'
  | 'Sevrage à faible risque de complication médicale (sevrage simple)'
  | 'Sevrage à fort risque de complication médicale (sevrage complexe)'
  | 'Saignée thérapeutique (phlébotomie)'
  | 'Suivi et soins d\'un état végétatif chronique ou d\'un état pauci relationnel'
  | 'Soins et traitement à domicile (hors HAD)'
  | 'Education thérapeutique du patient (ETP) labellisée'
  | 'Pose d\'anneau gastrique'
  | 'Gastroplastie verticale calibrée (sleeve gastrectomie)'
  | 'Dérivation biliopancréatique pour prise en charge de l\'obésité'
  | 'Sleeve gastrectomie'
  | 'Bypass gastrique'
  | 'Chirurgie plastique, esthétique de reconstruction (abdominoplastie)'
  | 'Prise en charge de l\'obésité modérée'
  | 'Prise en charge de l\'obésité sévère'
  | 'Prise en charge de l\'obésité morbide'
  | 'Thérapie de groupe ou atelier à médiation orale et-ou écrite'
  | 'Thérapie de groupe ou atelier à médiation artistique plastique'
  | 'Thérapie de groupe ou atelier à médiation sensorielle'
  | 'Thérapie de groupe ou atelier à médiation corporelle'
  | 'Thérapie de groupe ou atelier à médiation technique (jardinage, etc)'
  | 'Thérapie de groupe ou atelier à médiation animale'
  | 'Thérapie de groupe ou atelier à médiation artistique musicale'
  | 'Bilan d\'évaluation du comportement alimentaire'
  | 'Prise en charge des troubles conduites alimentaires (TCA) (anorexie, boulimie)'
  | 'Protonthérapie'
  | 'Tomographie d\'émission monophonique (TEMP)'
  | 'Tomographie par émission de positons'
  | 'Chirurgie excision-greffe cutanée'
  | 'Evaluation et traitement des brûlures thermiques et électriques'
  | 'Evaluation et traitement des brûlures chimiques'
  | 'Evaluation et traitement des brûlures radiques (irradiation)'
  | 'Evaluation et traitement des brûlures associées à des toxidermies sévères'
  | 'Evaluation et traitement des brûlures associées à d\'autes pathologies vvvermcato'
  | 'Prise en charge des séquelles fonctionnelles de brûlures'
  | 'Prise en charge des séquelles esthétiques de brûlures'
  | 'Suivi et rééducation des séquelles de brûlures chimiques'
  | 'Fibroscopie broncho-pulmonaire'
  | 'Traitement des plaies par pression négative (VAC)'
  | 'Confection, ajustement d\'orthèses, prothèses, vêtements cifs sur mesure'
  | 'Soin des plaies chroniques et pansements complexes sous anesthésie générale'
  | 'Evaluation expert brûlés'
  | 'Prise en charge du prurit séquellaire des brûlures'
  | 'Aide à l\'appropriation/réappropriation de l\'image corporelle (image de soi)'
  | 'RCP Appareil Digestif'
  | 'RCP App. Respi. Autres Thorax'
  | 'RCP Glandes Endocrines'
  | 'RCP Hématologie'
  | 'RCP Oeil'
  | 'RCP Org. génitaux féminins'
  | 'RCP Org. génitaux masculins'
  | 'RCP Os'
  | 'RCP Peau'
  | 'RCP Sein'
  | 'RCP Système Nerveux'
  | 'RCP Tissus mous NCA'
  | 'RCP VADS'
  | 'RCP Voies urinaires'
  | 'RCP Cancers rares'
  | 'RCP Douleur'
  | 'RCP Métastase osseuse'
  | 'RCP Oncogénétique'
  | 'RCP Oncogériatrie'
  | 'RCP Oncologie médicale'
  | 'RCP Préservation fertilité'
  | 'RCP Radio interventionnelle'
  | 'RCP Soins de support général'
  | 'RCP Soins palliatifs'
  | 'Examen d\'aptitude médicale des pilotes'
  | 'Spectroscopie'
  | 'Tractographie'
  | 'Réalisation de fistules artério-veineuses'
  | 'Désobstruction de fistules artério-veineuses'
  | 'Ablation de fistules artério-veineuses'
  | 'Suivi des troubles des apprentissages (troubles dys)'
  | 'Angioplastie des artères coronaires'
  | 'Angioplastie des troncs artériels supra-aortiques (TSAo) et Carotides'
  | 'Pontage des artères thoraco-abdomino-pelviennes'
  | 'Pontage des troncs supra aortiques'
  | 'Analgésie par hypnose'
  | 'Sédation par hypnose'
  | 'Chirurgie orthopédique du sportif professionnel'
  | 'Suivi antirabique (rage)'
  | 'Thérapie individuelle analytique (psychanalyse) et psychodynamique'
  | 'Thérapie individuelle psychosomatique'
  | 'Thérapie individuelle par relaxation'
  | 'Thérapie individuelle par hypnose'
  | 'Thérapie par EMDR (Eyes Movement Desensitization and Reprocessing)'
  | 'Thérapie individuelle cognitivo-comportementale (TCC)'
  | 'Thérapie de groupe analytique (psychanalyse) et psychodynamique'
  | 'Thérapie de groupe systémique (familiale, couple)'
  | 'Thérapie de groupe psychosomatique'
  | 'Thérapie de groupe par relaxation'
  | 'Thérapie de groupe par hypnose'
  | 'Thérapie de groupe cognitivo-comportementale (TCC)'
  | 'Thérapie de groupe ou atelier à médiation sportive'
  | 'Thérapie de groupe ou atelier médié'
  | 'Psychothérapie institutionnelle'
  | 'Art thérapie'
  | 'Remédiation cognitive'
  | 'Stimulation Magnétique Transcranienne Répétitive (RTMS)'
  | 'Balnéothérapie'
  | 'Bilan psychologique clinique'
  | 'Bilan ergothérapeutique'
  | 'Bilan neuro-psychologique'
  | 'Aide aux aidants (atelier pro-famille)'
  | 'Education thérapeutique du patient non labellisée ou psychoéducation'
  | 'Détection et intervention précoce pour la psychose'
  | 'Echographie transthoracique'
  | 'FAST échographie'
  | 'Annuloplastie percutanée'
  | 'Remplacement valvulaire aortique percutané (TAVI)'
  | 'Remplacement valvulaire mitral percutané'
  | 'Remplacement valvulaire pulmonaire percutané'
  | 'Réparation valvulaire percutanée par clip'
  | 'Décompression médullaire'
  | 'Echo-endoscopie des voies biliaires et du pancréas'
  | 'Endoscopie digestive haute (Fibroscopie oeso-gastro-duodénale (FOGD))'
  | 'Endoscopie digestive haute en urgence (fibroscopie oeso-gastro-duodénale (FOGD))'
  | 'Evaluation initiale après Accident avec Exposition au sang (AES)'
  | 'Suivi post Accident avec Exposition au Sang (AES)'
  | 'Insémination intra Utérine avec sperme de Donneur (IIU-D)'
  | 'Scolarisation sur site, maternelle'
  | 'Scolarisation sur site, élémentaire'
  | 'Scolarisation sur site, collège'
  | 'Scolarisation sur site, lycée'
  | 'Scolarisation sur site, formation supérieure'
  | 'Injection de toxine botulique (botulinique)'
  | 'Transfusion de produits sanguins labiles (PSL)'
  | 'Remplissage de pompe à Baclofène'
  | 'Administration de chimiothérapie par voie injectable'
  | 'Prise de mesure, ajustement et livraison d\'orthèses du membre inférieur'
  | 'Prise de mesure, ajustement et livraison de prothèses du membre inférieur'
  | 'Prise de mesure, ajustement et livraison de vêtements compressifs'
  | 'Prise de mesure, ajustement et livraison de conformateurs'
  | 'Hémodialyse sur site'
  | 'Ventilation invasive'
  | 'Ventilation non invasive'
  | 'Réadaptation phoniatrique'
  | 'Accompagnement au choix et à l\'ajustement d\'appareillages auditifs'
  | 'Apprentissage d\'un mode de communication augmentatif alternatif'
  | 'Choix et adaptation d\'un système de synthèse vocale'
  | 'Fabrication de poches à façon pour la nutrition entérale'
  | 'Nutrition entérale'
  | 'Fabrication de poches à façon pour la nutrition parentérale'
  | 'Apprentissage ou réapprentissage de la conduite automobile'
  | 'Exploration clinique complexe de la déglutition'
  | 'Accompagnement à la scolarisation hors site, maternelle'
  | 'Accompagnement à la scolarisation hors site, élémentaire'
  | 'Accompagnement à la scolarisation hors site, collège'
  | 'Accompagnement à la scolarisation hors site, lycée'
  | 'Accompagnement à la scolarisation hors site, formation supérieure'
  | 'Sédation consciente'
  | 'Réapprentissage de la cuisine'
  | 'Réadaptation équithérapique (sur site ou dans un centre partenaire)'
  | 'Exploration vésico-sphinctérienne (bilan urodynamique)'
  | 'Exploration ano-rectale'
  | 'Exploration génito-sexuelle'
  | 'Education thérapeutique'
  | 'Electroencéphalogramme (EEG)'
  | 'Electromyogramme (EMG)'
  | 'Analyse de l\'équilibre et de la posture'
  | 'Analyse du mouvement'
  | 'Monitoring foetal'
  | 'Oxygénothérapie hyperbare'
  | 'Mise en place d\'assistance circulatoire par l\'UMAC'
  | 'Imagerie fonctionnelle sans précision'
  | 'Echo-repérage par mise en place d\'un repère métallique'
  | 'Artériographie diagnostique'
  | 'Artériographie interventionnelle dans le territoire abdomino-pelvien'
  | 'Artériographie interventionnelle dans le territoire thoracique'
  | 'Artériographie interv. dans les territoires neuro-encéphalique et rachidien'
  | 'Echo-doppler transfontanellaire'
  | 'Entéro-scanner'
  | 'Transit du grêle'
  | 'Pantomographie'
  | 'Mammotome'
  | 'Tomosynthèse mammaire'
  | 'Thrombolyse artérielle'
  | 'Coloscanner et entéroscanner'
  | 'Déféco-IRM'
  | 'Echo-doppler artériel des membres'
  | 'Echo-doppler des troncs supra-aortiques (vaisseaux de la tête et du cou)'
  | 'Echo-doppler transcrânien'
  | 'Echo-doppler vasculaire d\'effort'
  | 'Echo-doppler veineux des membres'
  | 'Echographie de contraste vasculaire (dont endoprothèse, …)'
  | 'Colo-IRM et entéro-IRM'
  | 'Scanner dentaire'
  | 'IRM cardiaque (dont stress)'
  | 'Chirurgie du genou'
  | 'Chirurgie du bassin'
  | 'Chirurgie de l\'épaule'
  | 'Chirurgie du coude'
  | 'Chirurgie prothétique par ostéointégration'
  | 'Suivi post-accouchement - retour précoce à domicile'
  | 'Examen bébé-vision'
  | 'Addictologie et périnatalité'
  | 'Scintigraphie osseuse'
  | 'Lavage Broncho-Alvéolaire (LBA)'
  | 'Analyse observationnelle et tests cliniques de la marche'
  | 'Accompagnement à l\'insertion ou la réinsertion professionnelle'
  | 'Soins des plaies et pansements complexes ou longs (durée supérieure à 1h)'
  | 'Accompagnement au choix et à l\'ajustement des aides techniques basse vision'
  | 'Apprentissage d\'un mode de comm. augmentatif pour personne déf. aud.'
  | 'Apprentissage des techniques d\'aide à la mobilité pour personne déf. visuelle'
  | 'Mesure du volume vésical par échographe portable (Bladder-scan)'
  | 'Suivi de grossesse à risque'
  | 'Surveillance du nouveau-né à risque'
  | 'Confection d\'orthèse du membre supérieur'
  | 'Prise de mesure, ajustement et livraison d\'orthèses du membre supérieur'
  | 'Prise de mesure, ajustement et livraison d\'orthèses du rachis'
  | 'Prise de mesure, ajustement et livraison de prothèses du membre supérieur'
  | 'Vaporisation laser du col de l\'utérus'
  | 'Bladder Scan (scanner vésical à ultrasons)'
  | 'Audiogramme'
  | 'Réadaptation par réalité virtuelle'
  | 'Entéroscopie du grêle'
  | 'Actions de prévention primaire'
  | 'Actions de prévention secondaire'
  | 'Actions de prévention tertiaire'
  | 'Réadaptation des séquelles de brûlures'
  | 'Evaluation et prise en charge des séquelles de brûlures'
  | 'Bilan de la mastication et/ou de la déglutition'
  | 'Suivi diététique individualisé'
  | 'Education nutritionnelle'
  | 'Techniques d\'aide à la mastication/déglutition'
  | 'Evaluation et prise en charge de la douleur par une technique non invasive'
  | 'Prise en charge de la douleur réfractaire'
  | 'Evaluation / bilan cognitivo-comportemental'
  | 'Suivi bucco-dentaire avec organisation de la prise en charge'
  | 'Organisation de la prise en charge de la déficience visuelle associée'
  | 'Organisation de la prise en charge de la déficience auditive associée'
  | 'Soins de trachéotomie (jusqu\'à 3 aspirations/24h)'
  | 'Oxygénothérapie'
  | 'Assistance respiratoire, trachéotomie avec dépendance ventilatoire permanente'
  | 'Soins permanents continus / Présence IDE de nuit'
  | 'Suivi et organisation de la prise en charge d\'une dialyse péritonéale'
  | 'Suivi et organisation de la prise en charge d\'une hémodialyse'
  | 'Sondage vésical intermittent'
  | 'Soins de stomie d\'élimination digestive'
  | 'Soins de stomie d\'élimination urinaire'
  | 'Activités intergénérationnelles'
  | 'Psychothérapie'
  | 'Activité physique adaptée'
  | 'Parasport en compétition'
  | 'Pratique de communication augmentative-alternative'
  | 'Pratique de comm augmentative-alternative pour personne déficiente auditive'
  | 'Accompagnement logico-mathématique'
  | 'Atelier de stimulation cognitive dont atelier mémoire'
  | 'Atelier habileté sociale'
  | 'Accompagnement aux pratiques numériques et assistance informatique'
  | 'Accompagnement à l\'utilisation de tech numériques au service de la compensation'
  | 'Evaluation du logement'
  | 'Suivi de l\'adaptation du logement'
  | 'Accompagnement à l\'utilisation des équipements (dont domotique)'
  | 'Garde itinérante de nuit'
  | 'Garde à domicile de nuit'
  | 'Accompagnement administratif'
  | 'Entretien du logement (ménage, petit bricolage)'
  | 'Entretien du linge'
  | 'Accompagnement pour faire des achats (courses)'
  | 'Accompagnement ou apprentissage à la préparation du repas'
  | 'Transport accompagné véhiculé'
  | 'Soins et promenade d\'animaux domestiques'
  | 'Stage professionnel'
  | 'Adaptation du poste de travail en milieu ordinaire'
  | 'Activité professionnelle - Conditionnement, emballage, montage'
  | 'Activité professionnelle - Activités de services'
  | 'Activité professionnelle - Activités « vertes »'
  | 'Activité professionnelle - Entretien, second oeuvre'
  | 'Enseignement, Formation - Horticulture et Paysage'
  | 'Enseignement, Formation - Bâtiment, travaux publics et Electricité'
  | 'Enseignement, Formation - Distribution et vente'
  | 'Enseignement, Formation - Services administratifs et commerciaux'
  | 'Enseignement, Formation - Informatique et télécommunication'
  | 'Enseignement, Formation - Hôtellerie, Restauration et Tourisme'
  | 'Enseignement, Formation - Arts graphiques'
  | 'Enseignement, Formation - Mécanique'
  | 'Enseignement, Formation - Autres industries et Artisanat'
  | 'Enseignement, Formation - Transport et logistique'
  | 'Enseignement, Formation - Electronique et Automatisme'
  | 'Enseignement, Formation - Services aux personnes et aux collectivités'
  | 'Enseignement, Formation - Professions de la Santé et du Médico-social'
  | 'Enseignement, Formation - Chimie, biologie et biochimie'
  | 'Séance de préparation à la naissance et à la parentalité en groupe'
  | 'Accompagnement de la parentalité'
  | 'Médiation familiale'
  | 'Visite de convivialité'
  | 'Soutien et écoute téléphonique'
  | 'Acceptation d\'animaux aidants ou de compagnie'
  | 'Suivi des enfants vulnérables (réseau de santé en périnatalité)'
  | 'Enseignement Langage Parlé Complété (LPC)'
  | 'Enseignement Langue des Signes Française (LSF)'
  | 'Enseignement du Braille'
  | 'Enseignement dans un contexte de communication augmentative-alternative'
  | 'Enseignement Langue des Signes Française (LSF) tactile'
  | 'Groupes de soutien et d\'échange'
  | 'Méthode de détente activo-passive'
  | 'Téléassistance'
  | 'Prophylaxie pré-exposition par voie orale (PrEP)'
  | 'Evaluation pluri-professionnelle post-Accident Vasculaire Cérébral (AVC)'
  | 'Analyse instrumentale de la marche'
  | 'Analyse quantifiée du mouvement'
  | 'Prise en charge de l\'apnée du sommeil'
  | 'Exploration instrumentale de la déglutition'
  | 'Réentraînement à l\'effort avec surveillance instrumentale télémétrique'
  | 'Réentraînement à l\'effort avec monitoring complet portatif'
  | 'Réalisation et lecture d\'un holter ECG'
  | 'Accompagnement à l\'utilisation des transports en commun'
  | 'Accompagnement à la mobilité malvoyant'
  | 'Accompagnement au choix, ajustement des aides techniques'
  | 'Accompagnement de la fratrie'
  | 'Anatomie pathologie médico-légale'
  | 'Apprentissage ou rappel des règles de la sécurité routière'
  | 'Auto-immunité'
  | 'Biochimie des maladies métaboliques'
  | 'Biologie moléculaire infectieuse'
  | 'Dépistage de la trisomie 21 par les marqueurs sériques maternels'
  | 'Diagnostic prénatal non invasif (DPNI)'
  | 'Exploration des aplasies médullaires'
  | 'Foeto-pathologie'
  | 'Diagnostic intégré des leucémies et lymphomes'
  | 'Microbiologie : parasitologie'
  | 'Coordination pour assurer le suivi cardiologique avec organisation de la prise en charge'
  | 'Coordination pour assurer le suivi gynécologique avec organisation de la prise en charge'
  | 'Ténotomie percutanée'
  | 'Traitement des troubles de la mémoire'
  | 'Typage HLA'
  | 'Visite à domicile d\'évaluation des besoins de la personne et/ou des aidants'
  | 'Microbiologie : mycobactéries'
  | 'FIV avc Inj Intra Cytopla de Sperm morph sélec (IMSI)(Aide Méd à la Procré, AMP)'
  | 'Recherche de fragmentation de l\'ADN des spermatozoïdes'
  | 'Don de spermatozoïdes'
  | 'Don d\'ovocytes'
  | 'Préservation de la fertilité féminine/masculine'
  | 'Dépistage et suivi biologique des pathologies endocriniennes'
  | 'Diagnostic des pathologies plaquettaires'
  | 'Diagnostic des pathologies érythrocytaires'
  | 'Diagnostic des pathologies hémorragiques'
  | 'Diagnostic des pathologies thrombotiques'
  | 'Diagnostic de Thrombopénie à l\'héparine'
  | 'Potentiels évoqués visuels (PEV)'
  | 'Lithotritie des glandes salivaires'
  | 'Mesure de la pression des loges musculaires (syndrome des loges)'
  | 'Pachymétrie cornéenne'
  | 'Potentiels évoqués auditifs (PEA) et vestibulaires'
  | 'Potentiels évoqués somesthésiques cérébraux (PESc)'
  | 'Accompagnement de la personne en stage'
  | 'Accueil de stagiaire en stage pro ou de mise en situation pro'
  | 'Accueil de stagiaire en stage pré-professionnel'
  | 'Contrôle physico-chimique'
  | 'Electro-oculographie'
  | 'Rétinographie'
  | 'Electro-rétinographie'
  | 'Tomographie en cohérence optique'
  | 'Topographie cornéenne'
  | 'Animation socio-culturelle'
  | 'Aspiration trachéale'
  | 'Soins permanents continus par délégation / Présence aide-soignant de nuit'
  | 'Chirurgie sénologique'
  | 'Fermeture percutanée de CIA/FOP (communication inter-auriculaire)'
  | 'Fermeture percutanée d\'une CIV'
  | 'Endoscopie urologique (fibroscopie urétro-vésicale)'
  | 'Mesure de l\'indice bispectral (BIS)'
  | 'Réadaptation vésico-sphinctérienne'
  | 'Réadaptation des fonctions sexuelles et de la reproduction'
  | 'Réadaptation anorectale'
  | 'Aspiration gastrique'
  | 'Drainage bronchique'
  | 'Vaccination épidémie Grippe'
  | 'Dépistage du diabète'
  | 'Chirurgie de la cheville'
  | 'Chirurgie des tumeurs de l\'appareil locomoteur'
  | 'Chirurgie de la hanche'
  | 'Echo-endoscopie digestive'
  | 'Echographie digestive'
  | 'Coloscopie'
  | 'Ph-métrie'
  | 'Prise en charge alimentaire des pathologies digestives'
  | 'Proctologie médicale et instrumentale'
  | 'Proctologie médico-chirurgicale'
  | 'Prévention et gestion des maladies infectieuses transmissibles'
  | 'Veille sanitaire et vigilance (signalement Infections Associées aux Soins IAS)'
  | 'Prévention et intervention des Infections Associées aux Soins (IAS)'
  | 'Chimiothérapie intrathécale'
  | 'Soins de trachéotomie (plus de 3 aspirations/24h)'
  | 'Exploration fonctionnelle cardio-respiratoire au repos et à l\'effort'
  | 'Choc électrique externe (cardioversion électrique)'
  | 'Conciliation médicamenteuse'
  | 'Préparation centralisée des cytostatiques'
  | 'Fabrication de poche à façon pour la nutrition parentérale en néonatalogie'
  | 'Séquençage du génome viral'
  | 'Analyse automatique du sperme (CASA)'
  | 'Repérage des conduites addictives, soins et orientation'
  | 'Evaluation et suivi des addictions liées à l\'alcool'
  | 'Evaluation et suivi des addictions liées aux drogues'
  | 'Evaluation et suivi des addictions liées au tabac'
  | 'Evaluation et suivi des addictions liées aux jeux d\'argent et/ou au hasard'
  | 'Evaluation et suivi des addictions liées aux écrans'
  | 'Evaluation et suivi des addictions liées au sexe et/ou à la pornographie'
  | 'Evaluation et suivi des addictions liées au travail pathologique'
  | 'Evaluation et suivi des addictions liées au sport'
  | 'Evaluation et suivi des addictions liées aux achats compulsifs'
  | 'Initiation de traitement de substitution aux opiacés'
  | 'Test Rapide d’Orientation Diagnostique (TROD) VIH / Hépatite B / Hépatite C'
  | 'Echo-doppler artériel de l\'aorte'
  | 'MAPA sur 24h (Holter tensionnel)'
  | 'Enregistrement polygraphique dans le cadre du SAOS (ne plus utiliser)'
  | 'IRM de stress'
  | 'Scanner coronaire (ne plus utiliser)'
  | 'Choc électrique externe'
  | 'Artériographie des membres inférieurs'
  | 'Suivi conventionnel stimulateurs/défibrillateurs cardiaques (ne plus utiliser)'
  | 'Télésurveillance des prothèses rythmiques (ne plus utiliser)'
  | 'Chirurgie carcinologique pleurale'
  | 'Chirurgie carcinologique médiastinale'
  | 'Chirurgie carcinologique pariétale'
  | 'Chirurgie oesophagienne'
  | 'Chimiothérapie intra cavitaire hyperthermique'
  | 'Chirurgie de la cataracte - implants toriques, multifocaux et EDOF'
  | 'Chirurgie réparatrices du segment antérieur'
  | 'Chirurgie du kératocône'
  | 'Chirurgie cornéennes (laser et additives)'
  | 'Chirurgie intraoculaires (phaques et pseudophaques : presbytie)'
  | 'Chirurgie des paupières'
  | 'Tomographie en cohérence optique (OCT)'
  | 'Strabologie médicale'
  | 'Echographie ophtalmologique'
  | 'Réfractométrie de l\'enfant'
  | 'CAR-T Cells'
  | 'Radiothérapie stéréotaxique'
  | 'Neutronthérapie'
  | 'Pose de pompe intrathécale'
  | 'Evaluation multidimensionnelle standardisée'
  | 'Soins des chambres implantables'
  | 'Rééducation du cancer du sein'
  | 'Rééducation des cicatrices'
  | 'Réadaptation des troubles de la déglutition'
  | 'Rééducation de la main'
  | 'Réadaptation précoce suite d\'AVC'
  | 'Prise en charge des affections respiratoires chroniques'
  | 'Réadaptation de l\'amputé'
  | 'Rééducation maxillo-faciale'
  | 'Réadaptation vestibulaire (trouble de l\'équilibre)'
  | 'Rééducation de la Mucoviscidose'
  | 'Traitement des lymphoedèmes'
  | 'Evaluation des besoins d\'adaptation du véhicule'
  | 'Prise en charge de la lombalgie (protocole de coopération)'
  | 'Prise en charge de l\'entorse de la cheville (protocole de coopération)'
  | 'Rééducation du rachis avec éducation thérapeutique associée'
  | 'Réadaptation du rachis'
  | 'Sialendoscopie'
  | 'Diversion duodénale'
  | 'Exploration de la perméabilité des voies lacrymales'
  | 'Prise en charge directe SMUR'
  | 'Centre de référence labellisé'
  | 'Centre de compétence labellisé'
  | 'Structure spécialisée labellisée'
  | 'Téléconsultation'
  | 'Visite à domicile'
  | 'Tests allergologiques par patchs tests'
  | 'Tests cutanés allergologiques aux venins avec IDR'
  | 'Test de provocation par injection d\'un anesthésique local à concentration fixe'
  | 'Test de provocation par voie nasale'
  | 'Test de provocation par voie conjonctivale'
  | 'Test de provocation par contact labial'
  | 'Biopsie cutanée'
  | 'Tests cutanés allergologiques aux médicaments avec IDR'
  | 'Test de provocation orale à certains médicaments ou aliments sans gravité'
  | 'Tests de provocation orale'
  | 'Test de provocation par injection'
  | 'Initiation de désensibilisation aux hyménoptères par rush / semi-rush'
  | 'Test respiratoire à la méthacholine'
  | 'Expertise judiciaire'
  | 'Expertise à la demande des parties / expertise privée'
  | 'Chirurgie de la scoliose'
  | 'Installation et réglage d\'un appareil de ventilation non invasive (VNI)'
  | 'Suivi d\'un patient sous ventilation non invasive (VNI)'
  | 'Radiographie standard thorax'
  | 'Biopsie pleurale'
  | 'Mesure du transfert de monoxyde de carbone (TLCO)'
  | 'Traitement des lymphomes de haut grade'
  | 'Echographie pleurale'
  | 'Vaccination contre les infections sexuellement transmissibles (IST)'
  | 'Fourniture de matériel d\'hygiène, de prévention et de RdRD'
  | 'Surveillance de drainage pleural'
  | 'Présence médicale permanente 24/24'
  | 'Soins de kinésithérapie week-end et jours fériés assurés si besoin'
  | 'Surveillance post-chimiothérapie'
  | 'Surveillance post-radiothérapie'
  | 'Evaluation et prise en charge de la douleur par une technique invasive'
  | 'Echographie de l\'appareil locomoteur'
  | 'Ponction ou infiltration guidée par imagerie'
  | 'Injection de Plasma Riche en Plaquettes'
  | 'Mesure des Pressions de loges musculaires des membres inférieurs ou supérieurs'
  | 'Traitement par cryothérapie corps entier'
  | 'Colposcopie'
  | 'Échographie pelvienne'
  | 'Hystérosonographie'
  | 'Hystéro-sono-salpingosongraphie (HyFosy)'
  | 'Préservation ovocytaire'
  | 'Prise en charge médicale de la transidentité'
  | 'Traitement inducteur de l\'ovulation'
  | 'Chirurgie carcinologique intracrânienne'
  | 'Chirurgie muco-gingivale'
  | 'Extraction dentaire complexe'
  | 'Prise en charge bucco-dentaire de patients en situation de handicap'
  | 'Prise en charge bucco-dentaire sous anesthésie générale'
  | 'Prise en charge bucco-dentaire sous hypnose'
  | 'Prise en charge orthodontique des dysfonctions de l\'appareil manducateur'
  | 'Prise en charge orthodontique des syndromes crânio-faciaux'
  | 'Traitement des dysfonctions oro-faciales'
  | 'Téléradiographie'
  | 'Panoramique dentaire'
  | 'Prise en charge orthodontique des fentes oro-faciales'
  | 'Coordination de la prise en charge du COVID long'
  | 'Prise en charge SMTI - Soins Médico Techniques Importants'
  | 'Sondage vésical à demeure'
  | 'Service de transport lieu de vie - établissement'
  | 'Autopsie médico-scientifique'
  | 'Microscopie électronique'
  | 'Angiotomographie en cohérence optique (OCT A)'
  | 'Bilan d\'un handicap visuel'
  | 'Contactologie - lentille rigide'
  | 'Échographie du segment antérieur (UBM)'
  | 'Etude du Champ visuel (campimétrie, périmétrie)'
  | 'Microscopie spéculaire'
  | 'Orthokératologie'
  | 'Prise en charge des troubles neurovisuels des apprentissages'
  | 'Tomographie en cohérence optique (OCT) du segment antérieur'
  | 'Traitement du glaucome par trabeculoplastie sélective au laser (SLT)'
  | 'Actes pédiatriques réalisés sous sédation'
  | 'Exploration fonctionnelle respiratoire du jeune enfant'
  | 'Pléthysmographie du nourrisson'
  | 'Prise en charge des troubles du neuro-développement'
  | 'Surveillance périnatale et du trouble de l\'attachement'
  | 'Evaluation et réadaptation post-COVID (COVID long)'
  | 'Prise en charge des séquelles COVID long'
  | 'Réglage de stimulateur cérébral profond (dont Maladie de Parkinson)'
  | 'Réglage de stimulateur du nerf vague (VNS)'
  | 'Evaluation et suivi des addictions ou mésusages des médicaments'
  | 'Prise en charge en Appartements Thérapeutiques (AT)'
  | 'Prise en charge en Centres Thérapeutiques Résidentiels (CTR)'
  | 'Prise en charge en Communautés Thérapeutiques (CT)'
  | 'Prise en charge en Centre d\'Accueil d\'Urgence et de Transition (CAUT)'
  | 'Prise en charge en Appartements de Coordination Thérapeutique (ACT)'
  | 'Prise en charge en famille d\'accueil'
  | 'Fourniture de matériel d\'hygiène, de prévention et de RdRD par voie postale'
  | 'Accueil anonyme'
  | 'Prise en charge de la dégénérescence maculaire liée à l\'âge (DMLA)'
  | 'Accueil réservé aux femmes'
  | 'Délivrance de kits d\'antidote aux opioïdes'
  | 'Arthrographie'
  | 'Aponévrotomie percutanée plantaire (maladie de Ledderhose)'
  | 'Biopsie musculaire'
  | 'Bloc neurologique périphérique'
  | 'Infiltration disque intervertébral'
  | 'Imagerie par radiologie standard ostéoarticulaire'
  | 'Lavage articulaire'
  | 'Ponction aspiration de calcification sous repérage guidée par imagerie'
  | 'Podologie médicale (pathologies du pied)'
  | 'Recherche et lecture de microcristaux en microscopie optique'
  | 'Tractions élongations rachis, membre'
  | 'Traitement par ondes de choc extracorporelles'
  | 'Viscosupplémentation'
  | 'Appareillage des amputés'
  | 'Clinique du positionnement et de la mobilité avec nappes de pression'
  | 'Exploration neurophysiologique du périnée'
  | 'Infiltration articulaire, péri-tendineuse et péri-nerveuse sans guidage imagerie'
  | 'Infiltration du Hiatus sacro-coccygien'
  | 'Réadaptation des affections malformatives du système musculo-squelettique'
  | 'Réadaptation des affections médullaires'
  | 'Réadaptation des lésions cérébrales acquises'
  | 'Réadaptation des paralysies cérébrales et polyhandicaps'
  | 'Réadaptation des troubles neuro-développementaux'
  | 'Réadaptation post polio'
  | 'Réadaptation sensorielle'
  | 'Test au baclofène intrathécal'
  | 'Thérapie manuelle'
  | 'Abords vasculaires pour hémodialyse'
  | 'Chirurgie de l\'aorte abdominale ouverte et endovasculaire'
  | 'Chirurgie de l\'aorte thoracique endovasculaire'
  | 'Chirurgie de l\'aorte thoracique ouverte'
  | 'Chirurgie ouverte et endovasculaire des artères digestives et rénales'
  | 'Chirurgie du défilé cervico thoraco brachial'
  | 'Chirurgie vasculaire abdominale sous laparoscopie'
  | 'Chirurgie veineuse profonde ouverte et endovasculaire'
  | 'Embolisation d\'artères et d\'anévrismes hors neuro-vasculaire'
  | 'Embolisation de veines, de varices pelviennes, de varicocèle'
  | 'Embolisation fibrome utérin'
  | 'Oxymétrie trans cutanée'
  | 'Phlébographie diagnostique'
  | 'Chirurgie prothétique du genou'
  | 'Chirurgie ménisco ligamentaire du genou'
  | 'Prise en charge des infections ostéo-articulaires'
  | 'Participation aux gardes/astreintes'
  | 'Ablation d\'AC / FA (arythmie complète par fibrillation auriculaire)'
  | 'Ablation par radiofréquence de trouble ventriculaire'
  | 'Acte radiologique sous anesthésie générale'
  | 'Acte radiologique sous hypnose'
  | 'Angio IRM cérébrale'
  | 'Angio-mammographie'
  | 'Angioplastie, angioplastie-stenting et embolisation des artères rénales'
  | 'Angioscanner Tronc supra aortique et polygone de willis'
  | 'Arthro-distention'
  | 'Bilan radiologique avec prise en charge adaptée'
  | 'Imagerie de l\'endométriose'
  | 'Bilan radiologique d\'une dysfonction érectile'
  | 'Bilan radiologique d\'hypertension artérielle'
  | 'Biopsie prostatique sous échographie'
  | 'Biopsie rénale sous écho, TDM et IRM'
  | 'Biopsie sous IRM mammaire'
  | 'Block test anesthésique d\'un nerf périphérique guidé par l\'imagerie'
  | 'Cardiologie du sport'
  | 'Chimio-embolisation hépatique'
  | 'Chimiothérapie intrapéritonéale Pressurisée par Aérosols (PIPAC)'
  | 'Chirurgie carcinologique de l\'oesophage ou de la jonction gastro-oesophagienne'
  | 'Chirurgie de la cavité buccale'
  | 'Chirurgie de la surdité'
  | 'Chirurgie des amygdales par laser (coblation)'
  | 'Chirurgie des glandes salivaires'
  | 'Chirurgie des tumeurs cutanées de la face'
  | 'Chirurgie des voies aériennes de l\'enfant'
  | 'Chirurgie du frein de langue'
  | 'Chirurgie du rectum sous péritonéal'
  | 'Chirurgie percutanée du rein'
  | 'Chirurgie proctologique'
  | 'Contention souple d\'articulation'
  | 'Contrôle de l\'infection autour des dispositifs médicaux invasifs'
  | 'Cystosonographie pédiatrique'
  | 'Cytoponction thyroïdienne'
  | 'Dépistage de la déficience visuelle de l\'enfant'
  | 'Dépistage des surdités de l\'enfant'
  | 'Dépistage organisé de cancer bronchique'
  | 'Désobstruction tubaire'
  | 'Destruction de tumeur percutanée pulmonaire guidée par imagerie (DTPI)'
  | 'Destruction percutanée guidée par imagerie des tumeurs hépatiques et abdominales'
  | 'Destruction percutanée guidée par imagerie des tumeurs rénales'
  | 'Destruction percutanée guidée par IRM/échographie pour fibrome utérin'
  | 'Destruction tumorale (sphère ORL) sous guidage par imagerie'
  | 'Destruction tumorale percutanée mammaire guidée par imagerie'
  | 'Diagnostic par dermatoscope'
  | 'Diagnostic par echoscope doppler'
  | 'Drainage organes profonds abdominaux'
  | 'Echodoppler artériel / veineux'
  | 'Echographie clinique ciblée'
  | 'Échographie pelvienne pour PMA (compte folliculaire)'
  | 'Echographie thyroïdienne'
  | 'Elasto-IRM hépatique'
  | 'Embolisation (hémoptysie et malformation vasculaire)'
  | 'Embolisation cérébrale anévrisme Malformation Antéro Veineuse (MAV)'
  | 'Embolisation de la sphère ORL'
  | 'Embolisation des artères viscérales et digestives'
  | 'Embolisation prostatique pour HBP (hypertrophie bénigne de la prostate)'
  | 'Enucléation prostatique par laser'
  | 'Etablissement radiologique de l\'âge osseux'
  | 'Évacuation / Excision d\'une thrombose hémorroïdaire externe'
  | 'Suivi radiologique de cancer digestif (scanner IRM et critères RECIST)'
  | 'Examen médical d\'aptitude à la fonction publique par médecin agréé'
  | 'Examen médical du permis de conduire par médecin agréé'
  | 'Exploration de l\'endolymphe et de la périlymphe en IRM (maladie de Ménière)'
  | 'Exploration du nerf facial'
  | 'Exploration radiologique de la déglutition (ciné-radio)'
  | 'Exploration radiologique de la déglutition en ciné IRM'
  | 'Extraction des dents de sagesse'
  | 'Fermeture de l\'auricule gauche par voie percutanée'
  | 'FFR-CT (Fractional Flow Reserve Computed Tomography)'
  | 'Frottis du col utérin'
  | 'Gastrostomie percutanée'
  | 'Identification du caractère effectif du portage et de la contagiosité associée'
  | 'Imagerie pédiatrique avec anesthésie générale'
  | 'Imagerie post-mortem et virtopsie'
  | 'Implantation de pace maker double chambre'
  | 'Implantation de sphincter artificiel'
  | 'Incision / excision d\'un panaris superficiel'
  | 'Info du patient sur le risque infectieux associé à sa PEC ou son terrain'
  | 'Injection de toxine botulique guidée par imagerie (radio, écho ou scano-guidée)'
  | 'Injection toxine botulique'
  | 'Injections transtympaniques d\'agents pharmacologiques'
  | 'IRM Conduit Auditif Interne (CAI) et Angle Ponto-Cérébelleux (APC)'
  | 'IRM cérébrale multimodale (spectroscopie-perfusion-diffusion)'
  | 'IRM cérébrale pédiatrique'
  | 'IRM cérébraux orbitaires'
  | 'IRM de diffusion corps entier'
  | 'IRM de la statique périnéale'
  | 'IRM de perfusion et/ou de diffusion des tumeurs de la sphère ORL'
  | 'IRM de prostate paramétrique'
  | 'IRM fonctionnelle cérébrale'
  | 'IRM mammaire'
  | 'IRM médullaire enfant'
  | 'IRM neuro foetale'
  | 'IRM parenchyme pulmonaire mucoviscidose'
  | 'IRM pédiatrique corps entier'
  | 'IRM pelvienne dynamique (exploration des troubles de la statique pelvienne)'
  | 'IRM placentaire'
  | 'IRM rénale'
  | 'IRM thoracique'
  | 'Macrobiopsie mammaire guidée'
  | 'Mammographie de dépistage organisé'
  | 'Myélographie'
  | 'Myélo-scanner'
  | 'Ponction biopsie sous repérage guidé dans la sphère ORL'
  | 'Ponction lombaire guidée par imagerie'
  | 'Pose et retrait d’implants contraceptifs'
  | 'Pose et retrait de stérilet (DIU/SIU)'
  | 'Pose de holter implantable'
  | 'Pose de plâtres ou résines, orthèse'
  | 'Prescription initiale d\'audioprothèses'
  | 'Prise en charge des migraines et céphalées'
  | 'Prise en charge des vertiges et troubles de l\'équilibre'
  | 'Prise en charge radiologique d\'une amyotrophie spinale (injection intra-thécale)'
  | 'Prise en charge radiologique des suivis de chirurgie bariatrique'
  | 'Prise en charge sans rendez-vous'
  | 'Radio vasculaire diag. et interventionnelle des artères rénales et prostatiques'
  | 'Radio-embolisation'
  | 'Radiologie inter. Vasculaire (Tous territoires artériels et veineux hors NRI)'
  | 'Radiologie par CBCT (Imagerie Volumétrique par Faisceau Conique)'
  | 'Repérage scanner pour stéréotaxie'
  | 'Scanner artériel avec manoeuvres dynamiques'
  | 'Scanner cérébral pédiatrique sous anesthésie générale'
  | 'Scanner cérébral pédiatrique sous sédation'
  | 'Scanner pré Implantation d\'une valve aortique par voie percutanée (TAVI)'
  | 'Scanner spectral pour lithiase'
  | 'Scanner thoraco-abdomino-pelvien avec gastro-scanner'
  | 'Score calcique coronaire'
  | 'Sialo-IRM'
  | 'Simulation mobile de prévention des infections'
  | 'Sono-vaginographie'
  | 'Sutures cutanées'
  | 'Tamponnement nasal antérieur'
  | 'Téléexpertise en moins de 24h'
  | 'Téléexpertise en moins de 7 jours'
  | 'Téléexpertise en plus de 7 jours'
  | 'Thrombectomie cérébrale'
  | 'Traitement dermatologique à l\'azote'
  | 'Enregistrement polygraphique dans le cadre du SAOS'
  | 'Scanner coronaire'
  | 'Suivi conventionnel de stimulateurs/défibrillateurs cardiaques'
  | 'Télésurveillance médicale de l\'arythmie cardiaque'
  | 'Programme d\'ETP labellisée - Addictologie'
  | 'Programme d\'ETP labellisée - Affections neurologiques'
  | 'Programme d\'ETP labellisée - Diabète et pathologies endocrines'
  | 'Programme d\'ETP labellisée - Douleur'
  | 'Programme d\'ETP labellisée - Maladie rénale chronique (MRC), dialyse'
  | 'Programme d\'ETP labellisée - Maladies cardio-vasc et de l\'app circulatoire'
  | 'Programme d\'ETP labellisée - Maladies Cancéreuses'
  | 'Programme d\'ETP labellisée - Maladies de la nutrition'
  | 'Programme d\'ETP labellisée - Maladies du système digestif'
  | 'Programme d\'ETP labellisée - Maladies du système ostéoarticulaire'
  | 'Programme d\'ETP labellisée - Maladies infectieuses'
  | 'Programme d\'ETP labellisée - Maladies Neuro-musculaires'
  | 'Programme d\'ETP labellisée - Maladies respiratoires / Tabacologie'
  | 'Programme d\'ETP labellisée - ORL'
  | 'Programme d\'ETP labellisée - Polypathologie (plusieurs maladies)'
  | 'Programme d\'ETP labellisée - Psychiatrie et santé mentale'
  | 'Programme d\'ETP labellisée - Stomies'
  | 'Programme d\'ETP labellisée - Troubles du sommeil'
  | 'Programme d\'ETP labellisée - Exercice physique pour la santé'
  | 'Echographie 3D'
  | 'Échographie de datation de grossesse'
  | 'Echographie de mesure de la clarté nucale par PS agréé'
  | 'Échographie morphologique du 2ème trimestre'
  | 'Vérification échographique pré IVG (IPE)'
  | 'SMR Lab réadaptation des personnes en état de conscience altérée (ex EVC/EPR)'
  | 'SMR Labellisé réadaptation des patients amputés, appareillés ou non'
  | 'SMR Labellisé réadaptation PREcoce Post-Aiguë Cardiologique (PREPAC)'
  | 'SMR Labellisé réadaptation PREcoce Post-Aiguë Respiratoire (PREPAR)'
  | 'SMR Labellisé réadaptation neuro-orthopédique'
  | 'SMR Labellisé réadaptation SRPR'
  | 'SMR Labellisé réadaptation PREcoce Post-Aiguë Neurologique (PREPAN)'
  | 'SMR Lab réadap troubles cognitifs et comportementaux des patients cérébro-lésés'
  | 'SMR Labellisé réadaptation des lésions médullaires'
  | 'SMR Labellisé réadaptation des obésités complexes'
  | 'SMR Lab réadap troubles cognitifs sévères liés à une conduite addictive'
  | 'SMR Labellisé réadaptation du polyhandicap'
  | 'SMR Lab réadaptation troubles du langage et des apprentissages'
  | 'Chirurgie des traumatismes de la face'
  | 'Chirurgie esthétique des paupières'
  | 'Chirurgie fonctionnelle des paupières'
  | 'Chirurgie orthognatique et des malpositions des mâchoires'
  | 'Extraction dentaire simple'
  | 'Injection au visage de produit de comblement (dont acide hyaluronique)'
  | 'Endo. digestive diagnostique et interventionnelle : dissection sous-muqueuse'
  | 'Ph-métrie impédancemétrie'
  | 'Prise en charge nutritionnelle spécialisée des pathologies digestives'
  | 'Rhinoplastie'
  | 'Septoplastie'
  | 'Accompagnement de grossesse avec diabète gestationnel'
  | 'Accompagnement à la sexualité'
  | 'Diététique de la femme enceinte'
  | 'Echographie pour contrôle de stérilet'
  | 'Entretien postnatal précoce'
  | 'Entretien prénatal précoce'
  | 'Préparation à la naissance et à la parentalité'
  | 'Psychopérinatalité'
  | 'Rééducation pelvi-périnéale'
  | 'Retrait de Dispositif Intra-Utérin (DIU) (stérilet) ou d\'implant contraceptif'
  | 'Suivi à domicile de grossesse pathologique'
  | 'Surveillance de l\'ovulation'
  | 'Capillaroscopie'
  | 'Chimiothérapie des maladies auto-immunes'
  | 'Prise en charge de complication de biothérapie'
  | 'Exploration d\'un syndrome inflammatoire'
  | 'Prise en charge des maladies auto-inflammatoires'
  | 'Suivi de maladie systémique lors d\'une grossesse'
  | 'PEC des troubles de l\'hémostase et de la coagulation constitutionnels et acquis'
  | 'Programme d\'ETP labellisée - Maladies chroniques de la peau'
  | 'Analyse instrumentale de la course'
  | 'Prise en charge en Appartements de Coordination Thérapeutique (ACT) partagé'
  | 'Prise en charge en Appartements de Coordination Thérapeutique (ACT) individuel'
  | 'Accouchement à domicile'
  | 'Accouchement en maison de naissance'
  | 'Accouchement en plateau technique'
  | 'Bilan échographique pré FAV et suivi des abords vasculaires'
  | 'Diagnostic et prise en charge médicale de l\'insuffisance veineuse pelvienne'
  | 'Diagnostic et pec de l\'insuffisance veineuse des membres inf (dont varices)'
  | 'Echo-doppler du greffon rénal'
  | 'Echo-doppler des vaisseaux viscéraux'
  | 'Pharmaco-écho-doppler pénien'
  | 'Prise en charge et coordination de plaies et cicatrisations complexes'
  | 'Evaluation et prise en charge d\'analgésie intrathécale'
  | 'Thérapie individuelle ou de groupe dans le suivi de deuil'
  | 'Centre de recours pour chirurgie oncologique complexe'
  | 'Chirurgie oncologique du foie'
  | 'Chirurgie oncologique de l\'estomac'
  | 'Chirurgie oncologique du rectum'
  | 'Chirurgie oncologique des cancers thoraciques envahissants le rachis'
  | 'Chirurgie oncologique du coeur'
  | 'Chirurgie oncologique de la paroi thoracique'
  | 'Chirurgie oncologique des cancers urologiques avec atteinte vasculaire'
  | 'Chirurgie oncologique des cancers urologiques avec atteinte lombo-aortique'
  | 'Chirurgie oncologique des cancers gynécologiques avec atteinte péritonéale'
  | 'Chirurgie oncologique de l\'ovaire'
  | 'Prise en charge de la douleur liée à l\'endométriose'
  | 'Prise en charge de l\'infertilité liée à l\'endométriose'
  | 'Diagnostic de l\'endométriose complexe'
  | 'Filière endométriose - Premier niveau de recours'
  | 'Filière endométriose - Deuxième niveau de recours'
  | 'Filière endométriose - Troisième niveau de recours'
  | 'Evaluation psychiatrique pré-conceptionnelle'
  | 'Suivi psychiatrique de la femme enceinte'
  | 'Conseil en anti infectieux'
  | 'Gestion des complications de l\'infection par le VIH'
  | 'Initiation et suivi thérapeutique des hépatites virales'
  | 'Initiation, réévaluation et modification des anti rétroviraux'
  | 'Maladies vectorielles à tique (Lyme…)'
  | 'Prise en charge clinique des parasitoses'
  | 'Prise en charge des Infections chez les Immunodéprimés (ID)'
  | 'PEC diag et thérapeutique infections post-opé, sur prothèses, disp implantables'
  | 'Bilan diagnostic psychiatrique'
  | 'Prise en charge de l\'anorexie précoce prépubère'
  | 'Prise en charge de l\'hyperphagie boulimique'
  | 'Admission directe non programmée - PA'
  | 'Unité de réanimation pédiatrique de recours'
  | 'Accueil et prise en charge du polytraumatisé sévère'
  | 'Algologie périopératoire'
  | 'Anesthésie et médecine périopératoire des enfants de moins d\'un an'
  | 'Anesthésie et médecine périopératoire du nouveau-né (moins d\'un mois)'
  | 'Assistance circulatoire extracorporelle par ECMO'
  | 'Assistance respiratoire extracorporelle par ECMO'
  | 'Hypnose périopératoire'
  | 'Bilan des troubles psychotraumatiques répétés (dont TSPT)'
  | 'Bilan des troubles psychotraumatiques uniques (dont TSPT)'
  | 'Centre labellisé Covid-Long'
  | 'Chirurgie carcinologique de l\'oesophage'
  | 'Chirurgie des déformations thoraciques (pectum excavatum)'
  | 'Chirurgie du syndrome du défilé thoraco brachial'
  | 'Chirurgie fonctionnelle de l\'oesophage'
  | 'Entretien du logement (petit bricolage)'
  | 'Entretien du logement (petit jardinage)'
  | 'Implantation des stimulateurs diaphragmatiques'
  | 'Initiation des pompes externes à insuline'
  | 'Mesure continue du glucose (holter glycémique)'
  | 'Pathologie du métabolisme phosphocalcique'
  | 'Pontage coronarien à coeur battant'
  | 'Prise en charge de la douleur liée à une maladie cancéreuse'
  | 'Récupération améliorée après chirurgie (RAAC) orthopédique'
  | 'Récupération améliorée après chirurgie (RAAC) digestive'
  | 'Récupération améliorée après chirurgie (RAAC) gynécologique'
  | 'Suivi des pompes externes à insuline'
  | 'Traitement du psychotraumatisme'
  | 'Recherche d\'ADN foetal libre'
  | 'Centre de réhabilitation psychosociale - Centre de recours labellisé'
  | 'Centre de réhabilitation psychosociale - Centre de proximité labellisé'
  | 'Accompagnement à l\'éducation de l\'enfant sans violence éducative ordinaire (VEO)'
  | 'Accompagnement d\'un patient pour téléconsultation médicale'
  | 'Appui à l\'accueil inclusif (référent)'
  | 'Evaluation infirmière gériatrique multidimensionnelle'
  | 'Guidance parentale (psychoéducation)'
  | 'Index de pression systolique (IPS)'
  | 'Rédaction de certificat de décès'
  | 'Réalisation de "Mon bilan prévention"'
  | 'Prise en charge infirmière de récupération améliorée après chirurgie (RAAC)'
  | 'Prise en charge infirmière des douleurs chroniques'
  | 'Prise en charge infirmière des maladies psychiatriques'
  | 'Prise en charge infirmière des pathologies cardiaques'
  | 'Prise en charge infirmière des pathologies respiratoires'
  | 'Prise en charge infirmière des soins palliatifs'
  | 'Prise en charge infirmière des troubles vésico-sphinctériens (TVS)'
  | 'Prise en charge infirmière du diabète'
  | 'Référent santé et accueil inclusif des établissements d\'accueil du jeune enfant'
  | 'Prescription de vaccination'
  | 'Santé environnementale'
  | 'Soins infirmiers de dialyse péritonéale'
  | 'Accompagnement infirmier au changement'
  | 'Soins infirmiers d\'hémodialyse'
  | 'Repérage, accompagnement des troubles (neuro)développementaux et comportementaux'
  | 'Evaluation et suivi standardisé clinique et paraclinique des commotions cérébrales (Traumatisme Crânien Léger - TCL) dans un cadre sportif'
  | 'Soins et surveillance d\'administration de traitement hémophilique'
  | 'Soins et surveillance de remplissage de pompe à antalgique (dont morphine)'
  | 'Visite à domicile infirmière puéricultrice post-natale'
  | 'Exploration vasculaire d\'effort maximum chez le sportif'
  | 'Laximétrie dynamique automatisée du genou (LDA)'
  | 'Pressothérapie'
  | 'Diagnostic par télé-AVC'
  | 'Unité neuro-vasculaire (UNV) de territoire'
  | 'Unité neuro-vasculaire (UNV) de recours'
  | 'Délivrance de certificats médicaux pour le sport de haut niveau (SHN)'
  | 'Délivrance de certificats spécifiques pour les sportifs en situation de Handicap'
  | 'Evaluation de la vue du sportif'
  | 'Exploration clinique et fonctionnelle des intolérances d\'effort'
  | 'Exploration des anaphylaxies d\'exercice'
  | 'Mesure de la composition corporelle par DEXA'
  | 'Test de provocation à l\'asthme d\'effort'
  | 'Soins et surveillance des cathéters centraux (picc-line)'
  | 'Soins et surveillance des cathéters périnerveux'
  | 'Télésoin'
  | 'Analyse tridimensionnelle du mouvement, de la marche'
  | 'Accès direct IPA, kinésithérapeute, orthophoniste'
  | 'Prise en charge de la bronchiolite du nourrisson'
  | 'Rééducation des migraines et céphalées'
  | 'Rééducation abdominale du post partum'
  | 'Rééducation abdominale préopératoire et post opératoire'
  | 'Diathermie et électrothérapie combinées'
  | 'Cryothérapie compressive'
  | 'Télésurveillance médicale de l\'insuffisance cardiaque'
  | 'Télésurveillance médicale de la maladie rénale chronique (MRC)'
  | 'Télésurveillance médicale de l\'insuffisance respiratoire'
  | 'Télésurveillance médicale du diabète'
  | 'Télésurveillance médicale en oncologie'
  | 'Electrostimulation fonctionnelle urologique'
  | 'Filière Obésité - Niveau 1 Conventionné Centres Spécialisés Obésité (CSO)'
  | 'Filière Obésité - Niveau 2 Conventionné Centres Spécialisés Obésité (CSO)'
  | 'Filière Obésité - Niveau 3 Conventionné Centres Spécialisés Obésité (CSO)'
  | 'Filière Obésité - Niveau 3 (Centre Spécialisé Obésité)'
  | 'Consultation dans des locaux dédiés - personnes en situation de handicap (PH)'
  | 'Consultation sans locaux dédiés - personnes en situation de handicap (PH)'
  | 'HandiBloc'
  | 'Accompagnement des troubles de l\'écriture'
  | 'Accompagnement ergothérapique à l\'accès aux nouvelles technologies'
  | 'Accompagnement ergothérapique auprès des proches aidants (proches et professionnels) : apprentissage de techniques d\'accompagnement'
  | 'Accompagnement ergothérapique dans le cadre de déficiences visuelles'
  | 'Accompagnement ergothérapique dans le cadre de maladies neuro-évolutives (SLA, SEP, Parkinson, Alzheimer, PNM)'
  | 'Accompagnement ergothérapique dans le cadre de particularités sensorielles (TND)'
  | 'Accompagnement ergothérapique dans le cadre de pathologies neurologiques (AVC, TCE)'
  | 'Accompagnement ergothérapique de rééducation/réadaptation en situation de vie quotidienne post-hospitalisation (RAD)'
  | 'Accompagnement ergothérapique des troubles alimentaires'
  | 'Accompagnement ergothérapique pour la prévention de la chute et ses conséquences : désadaptation psychomotrice'
  | 'Evaluation et accompagnement à la mise en place de communication augmentative-alternative'
  | 'Programme de prévention primaire ergothérapique « Bien vieillir » (TaPasS)'
  | 'Accompagnement ergothérapique en milieu scolaire'
  | 'Accompagnement ergothérapique en réhabilitation psycho-sociale'
  | 'Evaluation et accompagnement ergothérapique au positionnement au fauteuil roulant (MCPAA) et positionnement au lit'
  | 'Accompagnement précoce des déficiences'
  | 'Consultation spécialisée en allaitement'
  | 'Consultations néonatales pédiatriques'
  | 'Dialyse longue nocturne'
  | 'Diathermie et électrothérapie combinées en soins pelvi-périnéaux'
  | 'Évaluation et adaptation diététique de nutrition artificielle'
  | 'Parcours surpoids et obésité pédiatrique « Mission : Retrouve ton Cap »'
  | 'Participation au dispositif HandiGynéco'
  | 'Séance de préparation à la naissance et à la parentalité individuelle'
  | 'Soin diététique et nutritionnel adulte pendant et après les traitements oncologiques'
  | 'Soin diététique et nutritionnel des alimentations pauvres en FODMAPs'
  | 'Soin diététique et nutritionnel des allergies alimentaires'
  | 'Soin diététique et nutritionnel des personnes en situation de handicap'
  | 'Soin diététique et nutritionnel des Troubles Alimentaires Pédiatriques (TAP)'
  | 'Soin diététique et nutritionnel des troubles de la déglutition ou dysphagies'
  | 'Soin diététique et nutritionnel pédiatrique pendant et après les traitements oncologiques'
  | 'Soin diététique et nutritionnel pour la gestion des troubles hormonaux (hypothyroïdie, SOPK, endométriose)'
  | 'Soin diététique et nutritionnel des diabètes'
  | 'Soins gynécologiques pour personnes en situation de handicap'
  | 'Suivi post-accouchement à domicile'
  | 'Suivi staturopondéral des nourrissons'
  | 'Surveillance d\'ictère néonatal par mesure transcutanée'
  | 'Test de Guthrie hors établissement (test néonatal du buvard)'
  | 'Vaccination contre la tuberculose'
  | 'Vaccination du calendrier vaccinal de l’adolescent et de l’adulte'
  | 'Vaccination du calendrier vaccinal du jeune enfant (0-12 ans)'
  | 'Vaccination du calendrier vaccinal du sénior'
  | 'Vaccination épidémie Covid'
  | 'Test Rapide d’Orientation Diagnostique (TROD) Covid-19'
  | 'Test Rapide d’Orientation Diagnostique (TROD) Grippe'
  | 'Test Rapide d’Orientation Diagnostique (TROD) Virus respiratoire syncytial (VRS)'
  | 'Test Rapide d’Orientation Diagnostique (TROD) Angine'
  | 'Test Rapide d’Orientation Diagnostique (TROD) Syphilis'
  | 'Test Rapide d’Orientation Diagnostique (TROD) Cystite'
  | 'Chirurgie de l’allongement osseux'
  | 'Correction des malformations congénitales de la main'
  | 'Accueil saisonnier possible'
  | 'Accueil saisonnier uniquement'
  | 'Autodialyse simple'
  | 'Autodialyse assistée'
  | 'Accueil en unité protégée'
  | 'Rééducation par réalité virtuelle'
  | 'Rééducation de l’amputé'
  | 'Rééducation vestibulaire (trouble de l’équilibre)'
  | 'Rééducation du rachis'
  | 'Rééducation des paralysies cérébrales et polyhandicaps'
  | 'Prise en charge de bébé grand prématuré (< 28 SA)'
  | 'Veille sanitaire et analyse de produit in situ'
  | 'Evaluation et suivi des addictions liées au cannabis et cannabinoïdes'
  | 'Evaluation et suivi des addictions liées aux psychostimulants (cocaïne, crack, dérivés des amphétamines, ecstasy, MDMA, cathinones de synthèse…)'
  | 'Evaluation et suivi des addictions liées aux opiacés (héroïne, morphinique)'
  | 'Evaluation et suivi des addictions liées aux autres substances (hallucinogènes, champignons, LSD, kétamine)'
  | 'Evaluation et suivi des addictions liées aux benzodiazépines et autres sédatifs'
  | 'Evaluation et suivi des addictions liées au chemsex (cathinones de synthèse, poppers, etc)'
  | 'Rééducation vésico-sphinctérienne'
  | 'Rééducation anorectale'
  | 'Rééducation des troubles de la déglutition'
  | 'Rééducation post-COVID (COVID long)'
  | 'Centre Ressources Autisme (CRA)'
  | 'Centre de référence des Troubles du Langage et de l’Apprentissage (CRTLA)'
  | 'Centre de référence du Trouble Déficit de l’Attention avec ou sans Hyperactivité (CRTDAH)'
  | 'Centre de compétence centre mémoire ressources et recherche (CMRR)'
  | 'Centre expert Parkinson'
  | 'Centre de ressources et de compétences sclérose en plaques (SEP)';

export interface FlattenedConcept {
  code: Code;
  display: Display;
  dateValid?: string;
  dateMaj?: string;
  status?: string;
  dateFin?: string;
  deprecationDate?: string;
}

export interface TerminologyData {
  resourceType: string;
  url: string;
  version: string;
  name: string;
  status: string;
  experimental: boolean;
  date: string;
  publisher: string;
  description: string;
  concept: Array<{
    code: Code;
    display: Display;
    property?: Array<{
      code: string;
      valueCode?: string;
      valueDateTime?: string;
      valueString?: string;
      valueBoolean?: boolean;
    }>;
  }>;
}

export type Data = TerminologyData;
