// @generated - DO NOT EDIT BY HAND
// To update this file, run: npm run update-sources

export type Code = 
  | 'G15_10'
  | 'G15_10/PAC00'
  | 'G15_10/SM01'
  | 'G15_10/SM02'
  | 'G15_10/SM03'
  | 'G15_10/SM04'
  | 'G15_10/SM05'
  | 'G15_10/SM06'
  | 'G15_10/SM07'
  | 'G15_10/SM08'
  | 'G15_10/SM09'
  | 'G15_10/SM10'
  | 'G15_10/SM11'
  | 'G15_10/SM12'
  | 'G15_10/SM13'
  | 'G15_10/SM14'
  | 'G15_10/SM15'
  | 'G15_10/SM16'
  | 'G15_10/SM17'
  | 'G15_10/SM18'
  | 'G15_10/SM19'
  | 'G15_10/SM20'
  | 'G15_10/SM21'
  | 'G15_10/SM22'
  | 'G15_10/SM23'
  | 'G15_10/SM24'
  | 'G15_10/SM25'
  | 'G15_10/SM26'
  | 'G15_10/SM27'
  | 'G15_10/SM28'
  | 'G15_10/SM29'
  | 'G15_10/SM30'
  | 'G15_10/SM31'
  | 'G15_10/SM32'
  | 'G15_10/SM33'
  | 'G15_10/SM34'
  | 'G15_10/SM35'
  | 'G15_10/SM36'
  | 'G15_10/SM37'
  | 'G15_10/SM38'
  | 'G15_10/SM39'
  | 'G15_10/SM40'
  | 'G15_10/SM41'
  | 'G15_10/SM42'
  | 'G15_10/SM43'
  | 'G15_10/SM44'
  | 'G15_10/SM45'
  | 'G15_10/SM46'
  | 'G15_10/SM47'
  | 'G15_10/SM48'
  | 'G15_10/SM49'
  | 'G15_10/SM50'
  | 'G15_10/SM51'
  | 'G15_10/SM52'
  | 'G15_10/SM53'
  | 'G15_10/SM54'
  | 'G15_10/SM55'
  | 'G15_10/SM56'
  | 'G15_10/SM57'
  | 'G15_10/SM58'
  | 'G15_10/SM59'
  | 'G15_10/SM60'
  | 'G15_10/SM61'
  | 'G15_10/SM62'
  | 'G15_10/SM63'
  | 'G15_10/SM64'
  | 'G15_10/SM65'
  | 'G15_10/SM66'
  | 'G15_10/SM67'
  | 'G15_10/SM68'
  | 'G15_10/SM69'
  | 'G15_10/SM70'
  | 'G15_10/SM71'
  | 'G15_10/SM72'
  | 'G15_10/SM73'
  | 'G15_10/SM74'
  | 'G15_10/SM75'
  | 'G15_10/SM76'
  | 'G15_10/SM77'
  | 'G15_10/SM78'
  | 'G15_10/SM79'
  | 'G15_10/SM80'
  | 'G15_10/SM81'
  | 'G15_10/SM82'
  | 'G15_10/SM83'
  | 'G15_10/SM84'
  | 'G15_10/SM85'
  | 'G15_10/SM86'
  | 'G15_10/SM87'
  | 'G15_10/SM88'
  | 'G15_10/SM89'
  | 'G15_10/SM90'
  | 'G15_10/SM91'
  | 'G15_10/SM92'
  | 'G15_10/SM93'
  | 'G15_10/SM94'
  | 'G15_10/SM95'
  | 'G15_10/CEX22'
  | 'G15_10/CEX24'
  | 'G15_10/CEX26'
  | 'G15_10/CEX64'
  | 'G15_10/SCH01'
  | 'G15_10/SCH02'
  | 'G15_10/SCH03'
  | 'G15_10/SCH04'
  | 'G15_10/SCH05'
  | 'G15_10/SCH06'
  | 'G15_10/SCH07'
  | 'G15_10/SCH08'
  | 'G15_10/SCH09'
  | 'G15_10/SCH10'
  | 'G15_10/SCH11'
  | 'G15_10/SCH12'
  | 'G15_10/SCH13'
  | 'G15_10/SCH14'
  | 'G15_10/SCH15'
  | 'G15_10/SCH16'
  | 'G15_10/SCH17'
  | 'G15_10/SCH18'
  | 'G15_10/SCH19'
  | 'G15_10/SCH20'
  | 'G15_10/SCH21'
  | 'G15_10/SCH22'
  | 'G15_10/SCH23'
  | 'G15_10/SCH24'
  | 'G15_10/SCH25'
  | 'G15_10/SCH26'
  | 'G15_10/SCH27'
  | 'G15_10/SCH28'
  | 'G15_10/SCH29'
  | 'G15_10/SCH30'
  | 'G15_10/SCH31'
  | 'G15_10/SCH32'
  | 'G15_10/SCH33'
  | 'G15_10/SCH34'
  | 'G15_10/SCH35'
  | 'G15_10/SCH36'
  | 'G15_10/SCH37'
  | 'G15_10/SCH38'
  | 'G15_10/SCH39'
  | 'G15_10/SCH40'
  | 'G15_10/SCH41'
  | 'G15_10/SCH42'
  | 'G15_10/SCH43'
  | 'G15_10/SCH44'
  | 'G15_10/SCH45'
  | 'G15_10/SCH46'
  | 'G15_10/SCH47'
  | 'G15_10/SCH48'
  | 'G15_10/SCH49'
  | 'G15_10/SCH50'
  | 'G15_10/SCH51'
  | 'G15_10/SCH52'
  | 'G15_10/SCH53'
  | 'G15_10/SCH54'
  | 'G15_10/SCH55'
  | 'G15_10/SCH56'
  | 'G15_10/SCH57'
  | 'G15_10/SCH58'
  | 'G15_10/SCH59'
  | 'G15_10/SCH60'
  | 'G15_10/C01'
  | 'G15_10/C03'
  | 'G15_10/C05'
  | 'G15_10/C07'
  | 'G15_10/C09'
  | 'G15_10/C10'
  | 'G15_10/C11'
  | 'G15_10/C12'
  | 'G15_10/C13'
  | 'G15_10/C15'
  | 'G15_10/C20'
  | 'G15_10/C23'
  | 'G15_10/C25'
  | 'G15_10/C27'
  | 'G15_10/C29'
  | 'G15_10/C30'
  | 'G15_10/C31'
  | 'G15_10/C33'
  | 'G15_10/C34'
  | 'G15_10/C35'
  | 'G15_10/C36'
  | 'G15_10/C37'
  | 'G15_10/C38'
  | 'G15_10/C39'
  | 'G15_10/C40'
  | 'G15_10/C41'
  | 'G15_10/C43'
  | 'G15_10/C45'
  | 'G15_10/C47'
  | 'G15_10/C51'
  | 'G15_10/C52'
  | 'G15_10/C54'
  | 'G15_10/C57'
  | 'G15_10/C58'
  | 'G15_10/C60'
  | 'G15_10/C62'
  | 'G15_10/C68'
  | 'G15_10/C69'
  | 'G15_10/C71'
  | 'G15_10/C72'
  | 'G15_10/C75'
  | 'G15_10/C76'
  | 'G15_10/C83'
  | 'G15_10/CAPA01'
  | 'G15_10/CAPA02'
  | 'G15_10/CAPA03'
  | 'G15_10/CAPA04'
  | 'G15_10/CAPA05'
  | 'G15_10/CAPA06'
  | 'G15_10/CAPA07'
  | 'G15_10/CAPA08'
  | 'G15_10/CAPA09'
  | 'G15_10/CAPA10'
  | 'G15_10/CAPA11'
  | 'G15_10/CAPA12'
  | 'G15_10/CAPA13'
  | 'G15_10/CAPA14'
  | 'G15_10/CAPA15'
  | 'G15_10/CAPA16'
  | 'G15_10/DSM200'
  | 'G15_10/DSM201'
  | 'G15_10/DSM202'
  | 'G15_10/DSM203'
  | 'G15_10/DSM204'
  | 'G15_10/DSM205'
  | 'G15_10/DSM206'
  | 'G15_10/DSM207'
  | 'G15_10/DSM208'
  | 'G15_10/DSM209'
  | 'G15_10/DSM210'
  | 'G15_10/DSM211'
  | 'G15_10/DSM212'
  | 'G15_10/DSM213'
  | 'G15_10/DSM214'
  | 'G15_10/DSM215'
  | 'G15_10/DSM216'
  | 'G15_10/DSM217'
  | 'G15_10/DSM218'
  | 'G15_10/DSM219'
  | 'G15_10/DSM220'
  | 'G15_10/DSM221'
  | 'G15_10/DSM222'
  | 'G15_10/DSM223'
  | 'G15_10/DSM224'
  | 'G15_10/DSM225'
  | 'G15_10/DSM226'
  | 'G15_10/DSM227'
  | 'G15_10/DSM228'
  | 'G15_10/DSM229'
  | 'G15_10/DSM230'
  | 'G15_10/DSM231'
  | 'G15_10/DSM232'
  | 'G15_10/DSM233'
  | 'G15_10/DSM234'
  | 'G15_10/DSM235'
  | 'G15_10/DSM236'
  | 'G15_10/DSM237'
  | 'G15_10/DSM238'
  | 'G15_10/DSM239'
  | 'G15_10/DSM240'
  | 'G15_10/80'
  | 'G15_10/81'
  | 'G15_10/DEC01'
  | 'G15_10/DEC02'
  | 'G15_10/DEC03'
  | 'G15_10/DEC04'
  | 'G15_10/DEC05'
  | 'G15_10/DEC06'
  | 'G15_10/DEC07'
  | 'G15_10/DEC08'
  | 'G15_10/DEC09'
  | 'G15_10/DEC10'
  | 'G15_10/DEC11'
  | 'G15_10/DEC12'
  | 'G15_10/DEC13'
  | 'G15_10/DEC14'
  | 'G15_10/DEC15'
  | 'G15_10/DEC16'
  | 'G15_10/DEC17'
  | 'G15_10/DEC18'
  | 'G15_10/DEC19'
  | 'G15_10/DEC20'
  | 'G15_10/DEC21'
  | 'G15_10/DEC22'
  | 'G15_10/DEC23'
  | 'G15_10/DEC24'
  | 'G15_10/SST01'
  | 'G15_10/SST02'
  | 'G15_10/SST03'
  | 'G15_10/SST04'
  | 'G15_10/SST05'
  | 'G15_10/SST06'
  | 'G15_10/SST07'
  | 'G15_10/SST08'
  | 'G15_10/SST09'
  | 'G15_10/SST10'
  | 'G15_10/SST11'
  | 'G15_10/SST12'
  | 'G15_10/SST13'
  | 'G15_10/SST14'
  | 'G15_10/SST15'
  | 'G15_10/SST16'
  | 'G15_10/SST17'
  | 'G15_10/SST18'
  | 'G15_10/SST19'
  | 'G15_10/SST20'
  | 'G15_10/SST21'
  | 'G15_10/SST22'
  | 'G15_10/SST23'
  | 'G15_10/SST24'
  | 'G15_10/SST25'
  | 'G15_10/SST26'
  | 'G15_10/SST27'
  | 'G15_21/FQ01'
  | 'G15_21/FQ02'
  | 'G15_21/FQ03'
  | 'G15_21/FQ04'
  | 'G15_21/FQ05'
  | 'G15_21'
  | 'G15_21/A'
  | 'G15_21/B'
  | 'G15_21/C'
  | 'G15_21/D'
  | 'G15_21/DA'
  | 'G15_21/DH'
  | 'G15_21/DM'
  | 'G15_21/E'
  | 'G15_21/EA'
  | 'G15_21/EB'
  | 'G15_21/EC'
  | 'G15_21/ED'
  | 'G15_21/EG'
  | 'G15_21/EH'
  | 'G15_21/G'
  | 'G15_21/H'
  | 'G15_21/M'
  | 'G15_26'
  | 'G15_28'
  | 'G15_31'
  | 'G15_32'
  | 'G15_35'
  | 'G15_36'
  | 'G15_37'
  | 'G15_38'
  | 'G15_39'
  | 'G15_40'
  | 'G15_40/SCD01'
  | 'G15_40/SCD02'
  | 'G15_40/SCD03'
  | 'G15_50'
  | 'G15_60'
  | 'G15_60/SI01'
  | 'G15_60/SI02'
  | 'G15_60/SI03'
  | 'G15_60/SI04'
  | 'G15_60/SI05'
  | 'G15_69'
  | 'G15_70'
  | 'G15_80'
  | 'G15_81'
  | 'G15_82'
  | 'G15_83'
  | 'G15_84'
  | 'G15_85'
  | 'G15_86'
  | 'G15_91'
  | 'G15_92'
  | 'G15_94'
  | 'G15_95'
  | 'G15_96'
  | 'G15_98'
  | 'G16_10'
  | 'G16_21'
  | 'G16_40'
  | 'G16_50';

export type Display = 
  | 'Médecin'
  | 'Médecin - Qualification Praticien adjoint contractuel (PAC)'
  | 'Médecin - Anatomie et Cytologie pathologiques (SM)'
  | 'Médecin - Anesthésie-réanimation (SM)'
  | 'Médecin - Biologie médicale (SM)'
  | 'Médecin - Cardiologie et maladies vasculaires (SM)'
  | 'Médecin - Chirurgie générale (SM)'
  | 'Médecin - Chirurgie maxillo-faciale (SM)'
  | 'Médecin - Chirurgie maxillo-faciale et Stomatologie (SM)'
  | 'Médecin - Chirurgie orthopédique et Traumatologie (SM)'
  | 'Médecin - Chirurgie infantile (SM)'
  | 'Médecin - Chirurgie plastique reconstruct et esthétique (SM)'
  | 'Médecin - Chirurgie thoracique et cardio-vasculaire (SM)'
  | 'Médecin - Chirurgie urologique (SM)'
  | 'Médecin - Chirurgie vasculaire (SM)'
  | 'Médecin - Chirurgie viscérale et digestive (SM)'
  | 'Médecin - Dermatologie et Vénéréologie (SM)'
  | 'Médecin - Endocrinologie et métabolisme (SM)'
  | 'Médecin - Génétique médicale (SM)'
  | 'Médecin - Gériatrie (SM)'
  | 'Médecin - Gynécologie médicale (SM)'
  | 'Médecin - Gynécologie-obstétrique (SM)'
  | 'Médecin - Hématologie (SM)'
  | 'Médecin - Hématologie, opt Maladie du sang (SM)'
  | 'Médecin - Hématologie, opt Onco-hématologie (SM)'
  | 'Médecin - Gastro-entérologie et hépatologie (SM)'
  | 'Médecin - Médecine du travail (SM)'
  | 'Médecin - Qualifié en Médecine Générale (SM)'
  | 'Médecin - Médecine interne (SM)'
  | 'Médecin - Médecine nucléaire (SM)'
  | 'Médecin - Médecine physique et réadaptation (SM)'
  | 'Médecin - Néphrologie (SM)'
  | 'Médecin - Neuro-chirurgie (SM)'
  | 'Médecin - Neurologie (SM)'
  | 'Médecin - Neuro-psychiatrie (SM)'
  | 'Médecin - ORL et Chirurgie cervico-faciale (SM)'
  | 'Médecin - Oncologie, opt Onco-hématologie (SM)'
  | 'Médecin - Oncologie, opt médicale (SM)'
  | 'Médecin - Oncologie, opt radiothérapie (SM)'
  | 'Médecin - Ophtalmologie (SM)'
  | 'Médecin - Oto-rhino-laryngologie (SM)'
  | 'Médecin - Pédiatrie (SM)'
  | 'Médecin - Pneumologie (SM)'
  | 'Médecin - Psychiatrie (SM)'
  | 'Médecin - Psychiatrie, opt enfant et adolescent (SM)'
  | 'Médecin - Radio-diagnostic (SM)'
  | 'Médecin - Radio-thérapie (SM)'
  | 'Médecin - Médecine intensive-réanimation (SM)'
  | 'Médecin - Recherche médicale (SM)'
  | 'Médecin - Rhumatologie (SM)'
  | 'Médecin - Santé publique et Médecine sociale (SM)'
  | 'Médecin - Stomatologie (SM)'
  | 'Médecin - Gynéco-obstétrique et Gynéco méd, opt Gyn-obs (SM)'
  | 'Médecin - Gynéco-obstétrique et Gynéco méd, opt Gyn-méd (SM)'
  | 'Médecin - Spécialiste en Médecine Générale (SM)'
  | 'Médecin - Médecine Générale (SM)'
  | 'Médecin - Radio-diagnostic et Radio-Thérapie (SM)'
  | 'Médecin - Chirurgie orale (SM)'
  | 'Médecin - Allergologie (SM)'
  | 'Médecin - Maladies infectieuses et tropicales (SM)'
  | 'Médecin - Médecine d\'urgence (SM)'
  | 'Médecin - Médecine légale et expertises médicales (SM)'
  | 'Médecin - Médecine vasculaire (SM)'
  | 'Médecin - Endocrinologie, diabétologie, nutrition (SM)'
  | 'Médecin - Biologie médicale option biologie générale (SM)'
  | 'Médecin - Biologie médicale option moléculaire, génétique et pharmacologie (SM)'
  | 'Médecin - Biologie médicale option hématologie et immunologie (SM)'
  | 'Médecin - Biologie médicale option agents infectieux (SM)'
  | 'Médecin - Biologie médicale option biologie de la reproduction (SM)'
  | 'Médecin - Chirurgie maxillo-faciale (réforme 2017) (SM)'
  | 'Médecin - Chirurgie pédiatrique option chirurgie viscérale pédiatrique (SM)'
  | 'Médecin - Chirurgie pédiatrique option orthopédie pédiatrique (SM)'
  | 'Médecin - Hématologie (réforme 2017) (SM)'
  | 'Médecin - Médecine interne et immunologie clinique (SM)'
  | 'Médecin - Médecine cardiovasculaire (SM)'
  | 'Médecin - Radiologie imagerie médicale (SM)'
  | 'Médecin - Santé publique (SM)'
  | 'Médecin - Anesthésie-réanimation opt anesthésie-pédiatrique (SM)'
  | 'Médecin - Chirurgie maxillo-faciale opt orthod dysmo max-fac (SM)'
  | 'Médecin - Chirurgie viscérale et digestive opt endo chir (SM)'
  | 'Médecin - Méd cardiovasculaire opt card interventionnelle (SM)'
  | 'Médecin - Méd cardiovasculaire opt imagerie cardio d\'expert (SM)'
  | 'Médecin - Méd cardiovasculaire opt rythmo inter stimu card (SM)'
  | 'Médecin - Médecine intensive-réanimation opt réa pédiatrique (SM)'
  | 'Médecin - Néphrologie option soins intensifs néphrologiques (SM)'
  | 'Médecin - Neurologie opt trait interv ischémie céréb aigüe (SM)'
  | 'Médecin - Ophtalmologie opt chir ophtalmopéd strabologique (SM)'
  | 'Médecin - ORL - chir cervico-faciale opt audiophonologie (SM)'
  | 'Médecin - Pédiatrie option néonatologie (SM)'
  | 'Médecin - Pédiatrie option neuropédiatrie (SM)'
  | 'Médecin - Pédiatrie option pneumopédiatrie (SM)'
  | 'Médecin - Pédiatrie option réanimation pédiatrique (SM)'
  | 'Médecin - Pneumologie option soins intensifs respiratoires (SM)'
  | 'Médecin - Psychiatrie option enfant et adolescent (SM)'
  | 'Médecin - Psychiatrie option psychiatrie de la personne âgée (SM)'
  | 'Médecin - Radiologie et imagerie médicale opt radio inter av (SM)'
  | 'Médecin - Santé publique option administration de la santé (SM)'
  | 'Médecin - Gynécologie médicale et obstétrique (CEX)'
  | 'Médecin - Gynécologie médicale (CEX)'
  | 'Médecin - Obstétrique (CEX)'
  | 'Médecin - Urologie (CEX)'
  | 'Médecin - Anatomie et cytologie pathologiques (SCH)'
  | 'Médecin - Anesthésie-réanimation (SCH)'
  | 'Médecin - Bactériologie-virologie, hygiène hosp (SCH)'
  | 'Médecin - Biochimie (SCH)'
  | 'Médecin - Biologie cellulaire, histologie, bio du dév (SCH)'
  | 'Médecin - Biologie médicale (SCH)'
  | 'Médecin - Biophysique (SCH)'
  | 'Médecin - Oncologie médicale (SCH)'
  | 'Médecin - Cardiologie et maladies vasculaires (SCH)'
  | 'Médecin - Chirurgie générale (SCH)'
  | 'Médecin - Chirurgie viscérale et digestive (SCH)'
  | 'Médecin - Chirurgie infantile (SCH)'
  | 'Médecin - Chirurgie maxillo-faciale (SCH)'
  | 'Médecin - Chirurgie orthopédique et Traumatologique (SCH)'
  | 'Médecin - Chirurgie plast reconstruct, esthétique (SCH)'
  | 'Médecin - Chirurgie thoracique et cardio-vasculaire (SCH)'
  | 'Médecin - Chirurgie urologique (SCH)'
  | 'Médecin - Chirurgie vasculaire (SCH)'
  | 'Médecin - Dermatologie et Vénéréologie (SCH)'
  | 'Médecin - Endocrinologie et Métabolisme (SCH)'
  | 'Médecin - Santé publique (SCH)'
  | 'Médecin - Explorations fonctionnelles (SCH)'
  | 'Médecin - Gastro-entérologie et Hépatologie (SCH)'
  | 'Médecin - Génétique (SCH)'
  | 'Médecin - Génétique médicale (SCH)'
  | 'Médecin - Gynécologie et Obstétrique (SCH)'
  | 'Médecin - Hématologie biologique (SCH)'
  | 'Médecin - Hématologie clinique (SCH)'
  | 'Médecin - Hémobiologie-transfusion (SCH)'
  | 'Médecin - Hygiène hospitalière (SCH)'
  | 'Médecin - Immunologie biologique (SCH)'
  | 'Médecin - Immunologie clinique (SCH)'
  | 'Médecin - Maladies infectieuses, maladies tropicales (SCH)'
  | 'Médecin - Médecine de la repro et Gynécologie médicale (SCH)'
  | 'Médecin - Médecine du travail (SCH)'
  | 'Médecin - Médecine d\'urgence (SCH)'
  | 'Médecin - Médecine générale (SCH)'
  | 'Médecin - Gériatrie (SCH)'
  | 'Médecin - Médecine interne (SCH)'
  | 'Médecin - Médecine légale (SCH)'
  | 'Médecin - Médecine nucléaire (SCH)'
  | 'Médecin - Médecine physique et de réadaptation (SCH)'
  | 'Médecin - Néphrologie (SCH)'
  | 'Médecin - neuro-chirurgie (SCH)'
  | 'Médecin - Neurologie (SCH)'
  | 'Médecin - Odontologie polyvalente (SCH)'
  | 'Médecin - Ophtalmologie (SCH)'
  | 'Médecin - Oto-rhino-laryngologie (SCH)'
  | 'Médecin - Parasitologie (SCH)'
  | 'Médecin - Pédiatrie (SCH)'
  | 'Médecin - Pharmacie polyvalente et Pharmacie hosp (SCH)'
  | 'Médecin - Pharmacologie clinique et Toxicologie (SCH)'
  | 'Médecin - Pneumologie (SCH)'
  | 'Médecin - Psychiatrie polyvalente (SCH)'
  | 'Médecin - Radiologie (SCH)'
  | 'Médecin - Oncologie radiothérapique (SCH)'
  | 'Médecin - Réanimation médicale (SCH)'
  | 'Médecin - Rhumatologie (SCH)'
  | 'Médecin - Stomatologie (SCH)'
  | 'Médecin - Toxicologie et Pharmacologie (SCH)'
  | 'Médecin - Anatomie et Cytologie pathologiques humaines (C)'
  | 'Médecin - Anesthésie-réanimation (C)'
  | 'Médecin - Médecine appliquée aux sports (C)'
  | 'Médecin - Cardiologie (C)'
  | 'Médecin - Chirurgie plast reconstruct, esthétique (C)'
  | 'Médecin - Chirurgie maxillo-faciale (C)'
  | 'Médecin - Chirurgie thoracique (C)'
  | 'Médecin - Chirurgie orthopédique (C)'
  | 'Médecin - Urologie (C)'
  | 'Médecin - Dermato-vénéréologie (C)'
  | 'Médecin - Hémobiologie (C)'
  | 'Médecin - Gynécologie médicale et Obstétrique (C)'
  | 'Médecin - Gynécologie médicale (C)'
  | 'Médecin - Obstétrique (C)'
  | 'Médecin - Maladies de l\'appareil digestif (C)'
  | 'Médecin - Néphrologie (C)'
  | 'Médecin - Médecine exotique (C)'
  | 'Médecin - Allergologie (C)'
  | 'Médecin - Angéiologie (C)'
  | 'Médecin - Cancérologie (C)'
  | 'Médecin - Diabétologie-nutrition (C)'
  | 'Médecin - Endocrinologie (C)'
  | 'Médecin - Maladies du sang (C)'
  | 'Médecin - Réanimation (C)'
  | 'Médecin - Médecine légale (C)'
  | 'Médecin - Médecine du travail (C)'
  | 'Médecin - Neurologie (C)'
  | 'Médecin - Neuro-chirurgie (C)'
  | 'Médecin - Neuro-psychiatrie (C)'
  | 'Médecin - Pédiatrie (C)'
  | 'Médecin - Phoniatrie (C)'
  | 'Médecin - Pneumologie (C)'
  | 'Médecin - Psychiatrie (C)'
  | 'Médecin - Psychiatrie, opt enfant et adolescent (C)'
  | 'Médecin - Médecine physique et réadaptation (C)'
  | 'Médecin - Rhumatologie (C)'
  | 'Médecin - Chirurgie pédiatrique (C)'
  | 'Médecin - Médecine nucléaire (C)'
  | 'Médecin - Médecine thermale (C)'
  | 'Médecin - Génétique médicale (C)'
  | 'Médecin - Endocrinologie et Maladies métaboliques (C)'
  | 'Médecin - Orthopédie dento-maxillo-faciale (C)'
  | 'Médecin - Chirurgie face et cou (C)'
  | 'Médecin - Addictologie clinique (CAPA)'
  | 'Médecin - Aide médicale urgente (CAPA)'
  | 'Médecin - Allergologie (CAPA)'
  | 'Médecin - Angéiologie (CAPA)'
  | 'Médecin - Evaluation et traitement de la douleur (CAPA)'
  | 'Médecin - Gérontologie (CAPA)'
  | 'Médecin - Hydrologie et climatologie médicales (CAPA)'
  | 'Médecin - Médecine aérospatiale (CAPA)'
  | 'Médecin - Médecine de catastrophe (CAPA)'
  | 'Médecin - Médecine et biologie du sport (CAPA)'
  | 'Médecin - Médecine de travail, prév risques prof (CAPA)'
  | 'Médecin - Médecine pénitentiaire (CAPA)'
  | 'Médecin - Médecine tropicale (CAPA)'
  | 'Médecin - Pratiques médico-judiciaires (CAPA)'
  | 'Médecin - Technologie transfusionnelle (CAPA)'
  | 'Médecin - Toxicomanies et Alcoologies (CAPA)'
  | 'Médecin - Addictologie (DNQ)'
  | 'Médecin - Allergologie et Immunologie clinique (DNQ)'
  | 'Médecin - Andrologie (DNQ)'
  | 'Médecin - Biochimie hormonale et métabolique (DNQ)'
  | 'Médecin - Biologie des agents infectieux (DNQ)'
  | 'Médecin - Biologie moléculaire (DNQ)'
  | 'Médecin - Cancérologie (DNQ)'
  | 'Médecin - Chirurgie de la face et du cou (DNQ)'
  | 'Médecin - Chirurgie plastique et reconstructrice (DNQ)'
  | 'Médecin - Chirurgie vasculaire (DNQ)'
  | 'Médecin - Cytogénétique humaine (DNQ)'
  | 'Médecin - Dermatopathologie (DNQ)'
  | 'Médecin - Foetopathologie (DNQ)'
  | 'Médecin - Gériatrie (DNQ)'
  | 'Médecin - Hématologie biologique (DNQ)'
  | 'Médecin - Hématologie maladies du sang (DNQ)'
  | 'Médecin - Hémobiologie-transfusion (DNQ)'
  | 'Médecin - Immunologie et Immunopathologie (DNQ)'
  | 'Médecin - Médecine de la reproduction (DNQ)'
  | 'Médecin - Médecine du sport (DNQ)'
  | 'Médecin - Médecine d\'urgence (DNQ)'
  | 'Médecin - Médecine légale et Expertises médicales (DNQ)'
  | 'Médecin - Médecine nucléaire (DNQ)'
  | 'Médecin - Médecine vasculaire (DNQ)'
  | 'Médecin - Néonatalogie (DNQ)'
  | 'Médecin - Neuropathologie (DNQ)'
  | 'Médecin - Nutrition (DNQ)'
  | 'Médecin - Orthopédie dento-maxillo-faciale (DNQ)'
  | 'Médecin - Pathologie infect et trop, clin et bio (DNQ)'
  | 'Médecin - Pharmacocinétique et Métabolisme des méd (DNQ)'
  | 'Médecin - Pharmacologie clin et Eval thérapeutiq (DNQ)'
  | 'Médecin - Psychiatrie de l\'enfant et de l\'ado (DNQ)'
  | 'Médecin - Radiopharmacie et radiobiologie (DNQ)'
  | 'Médecin - Réanimation médicale (DNQ)'
  | 'Médecin - Toxicologie biologique (DNQ)'
  | 'Médecin - Médecine de la douleur et Méd palliative (DNQ)'
  | 'Médecin - Cancérologie, opt Trait méd des cancers (DNQ)'
  | 'Médecin - Cancérologie, opt Chir cancérologique (DNQ)'
  | 'Médecin - Cancérologie, opt Réseaux cancérologie (DNQ)'
  | 'Médecin - Cancérologie, opt Biologie cancérologie (DNQ)'
  | 'Médecin - Cancérologie, opt Imagerie cancérologie (DNQ)'
  | 'Médecin - Homéopathie (OP)'
  | 'Médecin - Acupuncture (OP)'
  | 'Médecin - Addictologie (DEC)'
  | 'Médecin - Allergologie et immunologie clinique (DEC)'
  | 'Médecin - Andrologie (DEC)'
  | 'Médecin - Cancérologie option traitements médicaux des cancers (DEC)'
  | 'Médecin - Cancérologie option chirurgie cancérologique (DEC)'
  | 'Médecin - Cancérologie option réseaux de cancérologie (DEC)'
  | 'Médecin - Cancérologie option biologie en cancérologie (DEC)'
  | 'Médecin - Cancérologie option imagerie en cancérologie (DEC)'
  | 'Médecin - Dermatopathologie (DEC)'
  | 'Médecin - Foetopathologie (DEC)'
  | 'Médecin - Hémobiologie - tranfusion (DEC)'
  | 'Médecin - Médecine de la douleur et médecine palliative (DEC)'
  | 'Médecin - Médecine de la reproduction (DEC)'
  | 'Médecin - Médecine d\'urgence (DEC)'
  | 'Médecin - Médecine du sport (DEC)'
  | 'Médecin - Médecine légale et expertises médicales (DEC)'
  | 'Médecin - Médecine vasculaire (DEC)'
  | 'Médecin - Néonatologie (DEC)'
  | 'Médecin - Neuropathologie (DEC)'
  | 'Médecin - Nutrition (DEC)'
  | 'Médecin - Orthopédie dento-maxillo-faciale (DEC)'
  | 'Médecin - Pathologie infectieuse et tropicale, clinique et biologique (DEC)'
  | 'Médecin - Pharmacologie clinique et évaluation des thérapeutiques (DEC)'
  | 'Médecin - Psychiatrie de l\'enfant et de l\'adolescent (DEC)'
  | 'Médecin - Addictologie (SST)'
  | 'Médecin - Bio-informatique médicale (SST)'
  | 'Médecin - Cancérologie déc. hémato-cancérologie pédiatrique (SST)'
  | 'Médecin - Cancérologie traitements médicaux des cancers (SST)'
  | 'Médecin - Cardiologie pédiatrique et congénitale (SST)'
  | 'Médecin - Chirurgie de la main (SST)'
  | 'Médecin - Chirurgie en situation de guerre ou de catastrophe (SST)'
  | 'Médecin - Chirurgie orbito-palpébro-lacrymale (SST)'
  | 'Médecin - Douleur (SST)'
  | 'Médecin - Expertise médicale-préjudice corporel (SST)'
  | 'Médecin - Foetopathologie (SST)'
  | 'Médecin - Génétique et médecine moléculaire bioclinique (SST)'
  | 'Médecin - Hématologie bioclinique (SST)'
  | 'Médecin - Hygiène-prévention de l\'infection, résistances (SST)'
  | 'Médecin - Maladies allergiques (SST)'
  | 'Médecin - Médecine hospitalière polyvalente (SST)'
  | 'Médecin - Médecine palliative (SST)'
  | 'Médecin - Médecine scolaire (SST)'
  | 'Médecin - Médecine en situation de guerre ou en SSE (SST)'
  | 'Médecin - Médecine et biologie de la reproduction-andrologie (SST)'
  | 'Médecin - Médecine du sport (SST)'
  | 'Médecin - Nutrition appliquée (SST)'
  | 'Médecin - Pharmacologie médicale/thérapeutique (SST)'
  | 'Médecin - Sommeil (SST)'
  | 'Médecin - Thérapie cellulaire/transfusion (SST)'
  | 'Médecin - Urgences pédiatriques (SST)'
  | 'Médecin - Innovation et recherche en sciences biologiques et pharmaceutiques (SST)'
  | 'Pharmacien - Expérience prat. art. R.5124-16 du CSP Fabricant (FQ)'
  | 'Pharmacien - Expérience prat. art. R.5124-16 du CSP Exploitant (FQ)'
  | 'Pharmacien - Exp. prat. art. R.5124-16 du CSP Thérapie Cellulaire (FQ)'
  | 'Pharmacien - Expérience pratique article R.5124-18 du CSP (FQ)'
  | 'Pharmacien - Expérience pratique article R.5141-129 du CSP (FQ)'
  | 'Pharmacien'
  | 'Pharmacien titulaire d\'officine'
  | 'Pharmacien d\'entreprise - industrie'
  | 'Pharmacien d\'entreprise - distribution'
  | 'Pharmacien adjoint, remplaçant ou gérant'
  | 'Pharmacien adjoint'
  | 'Pharmacien d\'établissement de santé'
  | 'Pharmacien mutualiste ou minier'
  | 'Pharmacien d\'Outre-Mer'
  | 'Pharmacien titulaire d\'officine - OM'
  | 'Pharmacien d\'entreprise - industrie - OM'
  | 'Pharmacien d\'entreprise - distribution - OM'
  | 'Pharmacien adjoint - OM'
  | 'Pharmacien biologiste - OM'
  | 'Pharmacien d\'un établissement de santé - OM'
  | 'Pharmacien biologiste'
  | 'Pharmacien militaire'
  | 'Audioprothésiste'
  | 'Opticien-Lunetier'
  | 'Assistant dentaire'
  | 'Physicien médical'
  | 'Aide-soignant'
  | 'Ambulancier'
  | 'Auxiliaire de puériculture'
  | 'Préparateur en pharmacie hospitalière'
  | 'Préparateur en pharmacie (officine)'
  | 'Chirurgien-Dentiste'
  | 'Chirurgien-Dentiste - Orthopédie dento-faciale (SCD)'
  | 'Chirurgien-Dentiste - Chirurgie orale (SCD)'
  | 'Chirurgien-Dentiste - Médecine bucco-dentaire (SCD)'
  | 'Sage-Femme'
  | 'Infirmier'
  | 'Infirmier - Exercice infirmier en pratique avancée pathologies chroniques stabilisées (SI)'
  | 'Infirmier - Exercice infirmier en pratique avancée oncologie et hémato-oncologie (SI)'
  | 'Infirmier - Exerc. infirmier pratique avancée maladie rénale chroniq., dialyse, transp. rénale (SI)'
  | 'Infirmier - Exercice infirmier en pratique avancée santé mentale (SI)'
  | 'Infirmier - Exercice infirmier en pratique avancée urgences (SI)'
  | 'Infirmier psychiatrique'
  | 'Masseur-Kinésithérapeute'
  | 'Pédicure-Podologue'
  | 'Orthoprothésiste'
  | 'Podo-Orthésiste'
  | 'Orthopédiste-Orthésiste'
  | 'Oculariste'
  | 'Epithésiste'
  | 'Technicien de laboratoire médical'
  | 'Orthophoniste'
  | 'Orthoptiste'
  | 'Ergothérapeute'
  | 'Diététicien'
  | 'Psychomotricien'
  | 'Manipulateur ERM'
  | 'Médecin en formation'
  | 'Pharmacien en formation'
  | 'Chirurgien-Dentiste en formation'
  | 'Sage-Femme en formation';

export interface FlattenedConcept {
  code: Code;
  display: Display;
  dateValid?: string;
  dateMaj?: string;
  status?: string;
  dateFin?: string;
  deprecationDate?: string;
}

export interface TerminologyData {
  resourceType: string;
  url: string;
  version: string;
  name: string;
  status: string;
  experimental: boolean;
  date: string;
  publisher: string;
  description: string;
  concept: Array<{
    code: Code;
    display: Display;
    property?: Array<{
      code: string;
      valueCode?: string;
      valueDateTime?: string;
      valueString?: string;
      valueBoolean?: boolean;
    }>;
  }>;
}

export type Data = TerminologyData;
